**Imports**

In [ ]:
from google.colab import drive
import os
import pandas as pd

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import numpy as np

In [ ]:
from google.colab import userdata #to get the openAI API key
import json
import time
from tqdm import tqdm

In [ ]:
from openai import OpenAI

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
!pip install sacrebleu

Collecting sacrebleu
  Using cached sacrebleu-2.5.1-py3-none-any.whl.metadata (51 kB)
Collecting portalocker (from sacrebleu)
  Using cached portalocker-3.2.0-py3-none-any.whl.metadata (8.7 kB)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (2024.11.6)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (0.9.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (2.0.2)
Collecting colorama (from sacrebleu)
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (5.4.0)
Using cached sacrebleu-2.5.1-py3-none-any.whl (104 kB)
Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Using cached portalocker-3.2.0-py3-none-any.whl (22 kB)
Installing collected packages: portalocker, colorama, sacrebleu
Successfully installed colorama-0.4.6 portalocker-3.2.0 sacrebleu-2.5.1

In [ ]:
from sacrebleu.metrics import BLEU

In [ ]:
!pip install unbabel-comet==2.2.7

Collecting unbabel-comet==2.2.7
  Downloading unbabel_comet-2.2.7-py3-none-any.whl.metadata (19 kB)
Collecting entmax<2.0,>=1.1 (from unbabel-comet==2.2.7)
  Downloading entmax-1.3-py3-none-any.whl.metadata (348 bytes)
Requirement already satisfied: huggingface-hub<1.0,>=0.19.3 in /usr/local/lib/python3.12/dist-packages (from unbabel-comet==2.2.7) (0.35.3)
Collecting jsonargparse==3.13.1 (from unbabel-comet==2.2.7)
  Downloading jsonargparse-3.13.1-py3-none-any.whl.metadata (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.5/55.5 kB 2.7 MB/s eta 0:00:00
Collecting numpy<2.0.0,>=1.20.0 (from unbabel-comet==2.2.7)
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 4.5 MB/s eta 0:00:00
Requirement already satisfied: pandas>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from unbabel-comet==2.2.7) (2.2.2)
Collecting protobuf<5.0.0,>=4.24.4 (from unbabel-comet==2.2.7)
  Downloading protobuf-4.25.8-cp37-abi3-manylinux2014_x86_64.whl.metadata (541 bytes)
Collecting pytorch-lightning<3.0.0,>=2.0.0 (from unbabel-comet==2.2.7)
  Downloading pytorch_lightning-2.5.5-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: sacrebleu<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from unbabel-comet==2.2.7) (2.5.1)
Requirement already satisfied: scipy<2.0.0,>=1.5.4 in /usr/local/lib/python3.12/dist-packages (from unbabel-comet==2.2.7) (1.16.2)
Requirement already satisfied: sentencepiece<0.3.0,>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from unbabel-comet==2.2.7) (0.2.1)
Requirement already satisfied: torch>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from unbabel-comet==2.2.7) (2.8.0+cu126)
Collecting torchmetrics<0.11.0,>=0.10.2 (from unbabel-comet==2.2.7)
  Downloading torchmetrics-0.10.3-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: transformers<5.0,>=4.17 in /usr/local/lib/python3.12/dist-packages (from unbabel-comet==2.2.7) (4.57.1)
Requirement already satisfied: PyYAML>=3.13 in /usr/local/lib/python3.12/dist-packages (from jsonargparse==3.13.1->unbabel-comet==2.2.7) (6.0.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.19.3->unbabel-comet==2.2.7) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.19.3->unbabel-comet==2.2.7) (2025.3.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.19.3->unbabel-comet==2.2.7) (25.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.19.3->unbabel-comet==2.2.7) (2.32.4)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.19.3->unbabel-comet==2.2.7) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.19.3->unbabel-comet==2.2.7) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.19.3->unbabel-comet==2.2.7) (1.1.10)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.1->unbabel-comet==2.2.7) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.1->unbabel-comet==2.2.7) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.4.1->unbabel-comet==2.2.7) (2025.2)
Collecting lightning-utilities>=0.10.0 (from pytorch-lightning<3.0.0,>=2.0.0->unbabel-comet==2.2.7)
  Downloading lightning_utilities-0.15.2-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: portalocker in /usr/local/lib/python3.12/dist-packages (from sacrebleu<3.0.0,>=2.0.0->unbabel-comet==2.2.7) (3.2.0)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (from sacrebleu<3.0.0,>=2.0.0->unbabel-comet==2.2.7) (2024.11.6)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.12/dist-packages (from sacrebleu<3.0.0,>=2.0.0->unbabel-comet==2.2.7) (0.9.0)
Requirement already satisfied: colorama in /usr/local/lib/python3.12/dist-packages (from sacrebleu<3.0.0,>=2.0.0->unbabel-comet==2.2.7) (0.4.6)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from sacrebleu<3.0.0,>=2.0.0->unbabel-comet==2.2.7) (5.4.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->unbabel-comet==2.2.7) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->unbabel-comet==2.2.7) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->unbabel-comet==2.2.7) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->unbabel-comet==2.2.7) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->unbabel-comet==2.2.7) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->unbabel-comet==2.2.7) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->unbabel-comet==2.2.7) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->unbabel-comet==2.2.7) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->unbabel-comet==2.2.7) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->unbabel-comet==2.2.7) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->unbabel-comet==2.2.7) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->unbabel-comet==2.2.7) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->unbabel-comet==2.2.7) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->unbabel-comet==2.2.7) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->unbabel-comet==2.2.7) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->unbabel-comet==2.2.7) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->unbabel-comet==2.2.7) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->unbabel-comet==2.2.7) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->unbabel-comet==2.2.7) (3.4.0)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0,>=4.17->unbabel-comet==2.2.7) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0,>=4.17->unbabel-comet==2.2.7) (0.6.2)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2022.5.0->pytorch-lightning<3.0.0,>=2.0.0->unbabel-comet==2.2.7) (3.13.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.4.1->unbabel-comet==2.2.7) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.6.0->unbabel-comet==2.2.7) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.6.0->unbabel-comet==2.2.7) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub<1.0,>=0.19.3->unbabel-comet==2.2.7) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub<1.0,>=0.19.3->unbabel-comet==2.2.7) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub<1.0,>=0.19.3->unbabel-comet==2.2.7) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub<1.0,>=0.19.3->unbabel-comet==2.2.7) (2025.10.5)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning<3.0.0,>=2.0.0->unbabel-comet==2.2.7) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning<3.0.0,>=2.0.0->unbabel-comet==2.2.7) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning<3.0.0,>=2.0.0->unbabel-comet==2.2.7) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning<3.0.0,>=2.0.0->unbabel-comet==2.2.7) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning<3.0.0,>=2.0.0->unbabel-comet==2.2.7) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning<3.0.0,>=2.0.0->unbabel-comet==2.2.7) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2022.5.0->pytorch-lightning<3.0.0,>=2.0.0->unbabel-comet==2.2.7) (1.22.0)
Downloading unbabel_comet-2.2.7-py3-none-any.whl (90 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.0/91.0 kB 5.3 MB/s eta 0:00:00
Downloading jsonargparse-3.13.1-py3-none-any.whl (101 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.4/101.4 kB 5.9 MB/s eta 0:00:00
Downloading entmax-1.3-py3-none-any.whl (13 kB)
Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 54.3 MB/s eta 0:00:00
Downloading protobuf-4.25.8-cp37-abi3-manylinux2014_x86_64.whl (294 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.9/294.9 kB 13.3 MB/s eta 0:00:00
Downloading pytorch_lightning-2.5.5-py3-none-any.whl (832 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 832.4/832.4 kB 29.7 MB/s eta 0:00:00
Downloading torchmetrics-0.10.3-py3-none-any.whl (529 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 529.7/529.7 kB 13.9 MB/s eta 0:00:00
Downloading lightning_utilities-0.15.2-py3-none-any.whl (29 kB)
Installing collected packages: protobuf, numpy, lightning-utilities, jsonargparse, torchmetrics, entmax, pytorch-lightning, unbabel-comet
  Attempting uninstall: protobuf
    Found existing installation: protobuf 5.29.5
    Uninstalling protobuf-5.29.5:
      Successfully uninstalled protobuf-5.29.5
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opentelemetry-proto 1.37.0 requires protobuf<7.0,>=5.0, but you have protobuf 4.25.8 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
grpcio-status 1.71.2 requires protobuf<6.0dev,>=5.26.1, but you have protobuf 4.25.8 which is incompatible.
opencv-contrib-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
pytensor 2.35.1 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
ydf 0.13.0 requires protobuf<7.0.0,>=5.29.1, but you have protobuf 4.25.8 which is incompatible.
opencv-python-headless 4.12.0.88 requires numpy<2.3.0,>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
Successfully installed entmax-1.3 jsonargparse-3.13.1 lightning-utilities-0.15.2 numpy-1.26.4 protobuf-4.25.8 pytorch-lightning-2.5.5 torchmetrics-0.10.3 unbabel-comet-2.2.7

In [ ]:
from comet import download_model, load_from_checkpoint

In [ ]:
import time
import re

# **Dataset**

In [ ]:
df = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/WikiEn-Ara.xlsx')
df.head()

,id,english_text,arabic_text,Field,Link
0,1,William Barley (1565–1614) was an English book...,ويليام بارلي (1565 – 1614). كان بائع كُتب وناش...,"Business, economics, and finance biographies",https://en.wikipedia.org/wiki/William_Barley
1,2,"At this time, Cantillon became involved with B...",في هذا الوقت، أصبح كانتيلون مشاركاً مع التجاري...,"Business, economics, and finance biographies",https://en.wikipedia.org/wiki/Richard_Cantillon
2,3,"Harold Adams Innis FRSC (November 5, 1894 – No...",هارولد آدم اينيس (5 نوفمبر 1894- 8 نوفمبر 195...,"Business, economics, and finance biographies",https://en.wikipedia.org/wiki/Harold_Innis
3,4,"In computer science, binary search, also known...",في علم الحاسوب، خوارزمية البحث الثنائي ، المعر...,Computing,https://en.wikipedia.org/wiki/Binary_search_al...
4,5,The Manchester Mark 1 was one of the earliest ...,مانشتر مارك 1‏ كان واحدًا من أوائل حواسيب البر...,Computing,https://en.wikipedia.org/wiki/Manchester_Mark_1

In [ ]:
for text in df['english_text']:
  len += len(text.split())
print(len)

TypeError: 'int' object is not callable

In [ ]:
#drop the id column
df = df.set_index('id')
df.head()

,english_text,arabic_text,Field,Link
id,,,,
1,William Barley (1565–1614) was an English book...,ويليام بارلي (1565 – 1614). كان بائع كُتب وناش...,"Business, economics, and finance biographies",https://en.wikipedia.org/wiki/William_Barley
2,"At this time, Cantillon became involved with B...",في هذا الوقت، أصبح كانتيلون مشاركاً مع التجاري...,"Business, economics, and finance biographies",https://en.wikipedia.org/wiki/Richard_Cantillon
3,"Harold Adams Innis FRSC (November 5, 1894 – No...",هارولد آدم اينيس (5 نوفمبر 1894- 8 نوفمبر 195...,"Business, economics, and finance biographies",https://en.wikipedia.org/wiki/Harold_Innis
4,"In computer science, binary search, also known...",في علم الحاسوب، خوارزمية البحث الثنائي ، المعر...,Computing,https://en.wikipedia.org/wiki/Binary_search_al...
5,The Manchester Mark 1 was one of the earliest ...,مانشتر مارك 1‏ كان واحدًا من أوائل حواسيب البر...,Computing,https://en.wikipedia.org/wiki/Manchester_Mark_1

In [ ]:
df = df.rename(columns={'arabic_text':'arabic_reference'})
df.head()

,english_text,arabic_reference,Field,Link
id,,,,
1,William Barley (1565–1614) was an English book...,ويليام بارلي (1565 – 1614). كان بائع كُتب وناش...,"Business, economics, and finance biographies",https://en.wikipedia.org/wiki/William_Barley
2,"At this time, Cantillon became involved with B...",في هذا الوقت، أصبح كانتيلون مشاركاً مع التجاري...,"Business, economics, and finance biographies",https://en.wikipedia.org/wiki/Richard_Cantillon
3,"Harold Adams Innis FRSC (November 5, 1894 – No...",هارولد آدم اينيس (5 نوفمبر 1894- 8 نوفمبر 195...,"Business, economics, and finance biographies",https://en.wikipedia.org/wiki/Harold_Innis
4,"In computer science, binary search, also known...",في علم الحاسوب، خوارزمية البحث الثنائي ، المعر...,Computing,https://en.wikipedia.org/wiki/Binary_search_al...
5,The Manchester Mark 1 was one of the earliest ...,مانشتر مارك 1‏ كان واحدًا من أوائل حواسيب البر...,Computing,https://en.wikipedia.org/wiki/Manchester_Mark_1

**Information about the Dataset**

In [ ]:
len(df) #number of texts
unique_fields = df['Field'].unique()
print(unique_fields)
len(unique_fields)

['Business, economics, and finance biographies' 'Computing'
 'Culture and Society' 'Culture and society biographies ' 'Education '
 'Engineering and technology ' 'Health and medicine '
 'Heraldry, honors, and vexillology ' 'History ' 'Law' 'Law biographies '
 'Literature and theatre ' 'Autobiographies and memoirs '
 ' Magazines and comics ' 'Novels, including graphic novels '
 'Mathematics ' 'Biographies of mathematicians ' 'Media']

18

In [ ]:
field_counts = df['Field'].value_counts()
print(field_counts)
print(sum(field_counts.values))

Field
History                                         65
Culture and Society                             26
Novels, including graphic novels                19
Engineering and technology                      15
Culture and society biographies                 14
Autobiographies and memoirs                      8
Health and medicine                              6
Literature and theatre                           6
Education                                        5
Media                                            4
 Magazines and comics                            4
Computing                                        4
Law biographies                                  4
Business, economics, and finance biographies     3
Law                                              3
Heraldry, honors, and vexillology                2
Mathematics                                      1
Biographies of mathematicians                    1
Name: count, dtype: int64
190

Average number of words for English texts - Average number of words for Arabic texts - Standard deviation for both - Minimum and maximum lengths for both - Total word count for the entire corpus for both

In [ ]:
df['english_word_count'] = df['english_text'].str.split().str.len()
df['arabic_word_count'] = df['arabic_reference'].str.split().str.len()
df

,english_text,arabic_reference,Field,Link,english_word_count,arabic_word_count
id,,,,,,
1,William Barley (1565–1614) was an English book...,ويليام بارلي (1565 – 1614). كان بائع كُتب وناش...,"Business, economics, and finance biographies",https://en.wikipedia.org/wiki/William_Barley,131,111
2,"At this time, Cantillon became involved with B...",في هذا الوقت، أصبح كانتيلون مشاركاً مع التجاري...,"Business, economics, and finance biographies",https://en.wikipedia.org/wiki/Richard_Cantillon,131,108
3,"Harold Adams Innis FRSC (November 5, 1894 – No...",هارولد آدم اينيس (5 نوفمبر 1894- 8 نوفمبر 195...,"Business, economics, and finance biographies",https://en.wikipedia.org/wiki/Harold_Innis,76,87
4,"In computer science, binary search, also known...",في علم الحاسوب، خوارزمية البحث الثنائي ، المعر...,Computing,https://en.wikipedia.org/wiki/Binary_search_al...,211,197
5,The Manchester Mark 1 was one of the earliest ...,مانشتر مارك 1‏ كان واحدًا من أوائل حواسيب البر...,Computing,https://en.wikipedia.org/wiki/Manchester_Mark_1,117,109
...,...,...,...,...,...,...
186,Georg Ferdinand Ludwig Philipp Cantor was a ma...,غيورغ فرديناند لودفيغ فيليب كانتور عاش ما بين ...,Biographies of mathematicians,https://en.wikipedia.org/wiki/Georg_Cantor,97,90
187,"""From the Doctor to My Son Thomas"" is a viral ...",من الطبيب إلى إبني توماس هو فيديو مسجل من المم...,Media,https://en.wikipedia.org/wiki/From_the_Doctor_...,86,77
188,Street newspapers (or street papers) are newsp...,جرائد الشارع (أو صحف الشارع) هي جرائد ومجلات ي...,Media,https://en.wikipedia.org/wiki/Street_newspaper,182,153
189,"The first season of True Detective, an America...",محقق فذ مسلسل تلفزيوني درامي درامي أمريكي مختا...,Media,https://en.wikipedia.org/wiki/True_Detective_(...,79,68
190,Union Films was a film production company loca...,أفلام يونيون كانت شركة الإنتاج السينمائي الموج...,Media,https://en.wikipedia.org/wiki/Union_Films,70,67

In [ ]:
statistics = {
    'English': {
        'total': df['english_word_count'].sum(),
        'min': df['english_word_count'].min(),
        'max': df['english_word_count'].max(),
        'mean': df['english_word_count'].mean(),
        'std': df['english_word_count'].std() },
    'Arabic': {
        'total': df['arabic_word_count'].sum(),
        'min': df['arabic_word_count'].min(),
        'max': df['arabic_word_count'].max(),
        'mean': df['arabic_word_count'].mean(),
        'std': df['arabic_word_count'].std()}}
statistics

{'English': {'total': 22126,
  'min': 30,
  'max': 259,
  'mean': 116.45263157894736,
  'std': 47.408339502811245},
 'Arabic': {'total': 19955,
  'min': 30,
  'max': 264,
  'mean': 105.02631578947368,
  'std': 45.018565742225164}}

In [ ]:
train_df, test_df= train_test_split(df, test_size=0.2, random_state=42)
print(train_df.shape[0])
print(test_df.shape[0])

152
38

# **Systems Under Evaluation**

# **Large Language Model (GPT 5.0 mini)**

In [ ]:
openAI_Key = userdata.get('NMT_GPT5mini')

In [ ]:
client = OpenAI(api_key=openAI_Key)

In [ ]:
system_prompt = """
You are an expert translator specializing in English to Modern Standard Arabic translations. Your goal is to produce high-quality, accurate translations that are culturally appropriate, stylistically natural, and aligned with professional standards as per ISO 17100.
Purpose: Produce translations of encyclopedic Wikipedia excerpts for evaluation in a machine translation research.
Target Audience: Arabic-speaking general readers.
Style: Encyclopedic.
Language Pair: English to Modern Standard Arabic.
Domain Context: The text is from a Wikipedia article in the field of {field}.
Here are five high-quality example translations to guide your output:
Example 1 (Field: History):
English: The Palace of Versailles is a royal château in Versailles, Yvelines, in the Île-de-France region of France. When the château was built, Versailles was a country village; today, however, it is a suburb of Paris, some 20 kilometres southwest of the French capital. The court of Versailles was the centre of political power in France from 1682, when Louis XIV moved from Paris, until the royal family was forced to return to the capital in October 1789 after the beginning of the French Revolution. Versailles is therefore famous not only as a building, but as well as a symbol of the system of absolute monarchy of the Ancien Régime.
Arabic: قصر فرساي هو قلعة ملكية تقع في فرساي في منطقة إيل دو فرانس الفرنسية. عندما بُنيت القلعة، كانت فرساي مجرد قرية؛ ولكن اليوم تُعتبر فرساي من ضواحي باريس وتبعد حوالي عشرين كيلومترًا عن العاصمة الفرنسية. كان بلاط فرساي مركزًا للسلطة السياسية في فرنسا من عام 1682، عندما قرر لويس الرابع عشر الانتقال من باريس، حتى أجبِرت العائلة الملكية على العودة إلى العاصمة في أكتوبر 1789 بعد بداية الثورة الفرنسية. لا تُعد فرساي مجرد مبنى شهير بل رمزًا لنظام الملكية المطلقة للنظام القديم
Example 2 (Field: Law):
English: The Coinage Act of 1965, Pub. L. 89–81, 79 Stat. 254, enacted July 23, 1965, eliminated silver from the circulating United States dime (ten-cent piece) and quarter dollar coins. It also reduced the silver content of the half dollar from 90 percent to 40 percent; silver in the half dollar was subsequently eliminated by a 1970 law.
Arabic: قانون العملة لعام 1965، 254، صدر في 23 يوليو/تموز 1965، وألغى الفضة من العُملات المعدنية فئة العشرة سنتات و الربع دولار المتداولة في الولايات المتحدة. كما أدى ذلك إلى خفض محتوى الفضة في نصف الدولار من 90 في المائة إلى 40 في المائة؛ وألغى بعد ذلك الفضة في نصف الدولار بموجب قانون صدر عام 1970
Example 3 (Field: Magazines and comics):
English: Alice in the Country of Hearts is a Japanese female-oriented visual novel developed by Quin Rose. The game is a re-imagining of Lewis Carroll's classic 1865 novel Alice's Adventures in Wonderland. There are multiple sequel games, as well as multiple manga series, licensed in North America originally by Tokyopop and later by Yen Press and Seven Seas Entertainment. An original video animation adaptation was announced for release in November 2008, but was later delayed. Instead, an anime film adaptation produced by Asahi Production was released in Japanese theaters in July 2011.
Arabic: أليس في بلاد القلوب هي رواية مرئية يابانية مغامرة رومانسية موجهة للإناث، طورت من قِبل كوين روز. اللعبة هي إعادة تخيل لرواية لويس كارول الكلاسيكية: مغامرات أليس في بلاد العجائب. كانت هناك عدة تتمات للعبة، فضلا عن العديد من سلاسل مانغا. فيديو رسوم متحركة أصلي أعلن عن موعد إصداره في نوفمبر 2008، ولكن تم تأجيل الإطلاق في وقت لاحق. فيلم أنمي من إنتاج اساهي برودكشن صدر في المسارح اليابانية في يوليو 2011
Example 4 (Field: Novels)
English: A debut novel is the first novel a novelist publishes. Debut novels are often the author's first opportunity to make an impact on the publishing industry, and thus the success or failure of a debut novel can affect the ability of the author to publish in the future. Sometimes new novelists will self-publish their debut novels, because publishing houses will not risk the capital needed to market books by an unknown author to the public.
Arabic: الرواية الأولى هي أول عمل روائي منشور للكاتب، وغالبًا ما تُشكّل الفرصة الأولى له لإثبات حضوره في عالم النشر. يمكن لنجاح أو فشل هذه الرواية أن يؤثر بشكل مباشر على قدرة الكاتب على الاستمرار في النشر مستقبلاً. في كثير من الحالات، يلجأ الروائيون الجدد إلى نشر رواياتهم الأولى بأنفسهم، نظرًا لتردد دور النشر في المخاطرة بالاستثمار في أعمال لكتاب غير معروفي
Example 5 (Field: Education)
English: The Education Program for Gifted Youth (EPGY) at Stanford University was a loose collection of gifted education programs formerly located within Stanford Pre-Collegiate Studies program.[1] EPGY included distance and residential summer courses for students of all ages. Many of the courses were distance learning, meaning that courses were taught remotely via the Internet, rather than in the traditional classroom setting. Courses targeted students from elementary school up to advanced college graduate. Subjects offered included: Mathematics, English, Humanities, Physics, and Computer Science. Stanford Pre-Collegiate Studies is similar to the Center for Talented Youth at the Johns Hopkins University in terms of certain objectives.
Arabic: برنامج التعليم للشباب الموهوبين (EPGY) في جامعة ستانفورد، هو مجموعة فضفاضة من برامج التعليم للموهوبين التي كانت موجودة سابقا في دراسات ستانفورد قبل الجامعية في جامعة ستانفورد. وشملت برامج إبغي دورات المسافة والصيف السكنية للطلاب من جميع الأعمار. وكان العديد من الدورات التعلم عن بعد، وهذا يعني أن الدورات تدرس عن بعد عن طريق الإنترنت، وليس في إعدادالفصول الدراسية التقليدية. دورات استهدفت الطلاب من المدرسة الابتدائية حتى خريج الكلية المتقدمة. الموضوعات المقدمة شملت: الرياضيات، واللغة الإنجليزية، والعلوم الإنسانية، والفيزياء، وعلوم الكمبيوتر. تشبه دراسات ستانفورد ما قبل الجامعية مركز الشباب الموهوبين في جامعة جونز هوبكنز من حيث الأهداف المعينة
Output only the Arabic translation without any additional explanations or text.
"""

In [ ]:
def gpt_translate(text_english, text_field):
    gpt_prompt = system_prompt.format(field=text_field)
    try:
        response = client.chat.completions.create(
            model="gpt-5-mini",
            messages=[
                {"role": "system", "content": gpt_prompt},
                {"role": "user", "content": text_english}
            ],
            max_completion_tokens=4096,  # Changed from max_tokens
            n=1,
            stop=None,
        )
        arabic_translation = response.choices[0].message.content.strip()
        return arabic_translation
    except Exception as e:
        print("Error during translation:", str(e))
        return None

In [ ]:
train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)  # Stratify by Field if possible

In [ ]:
for split in [train_df, test_df]:split['gpt_translation'] = np.nan

In [ ]:
'''for index, row in tqdm(train_df.iterrows(), total = len(train_df), desc="Translating train_df"):
  translation = gpt_translate(row['english_text'], row['Field'])
  train_df.at[index, 'gpt_translation'] = translation
  if translation is None:
        print(f"Failed translation for ID {index}")'''

'for index, row in tqdm(train_df.iterrows(), total = len(train_df), desc="Translating train_df"):\n  translation = gpt_translate(row[\'english_text\'], row[\'Field\'])\n  train_df.at[index, \'gpt_translation\'] = translation\n  if translation is None:\n        print(f"Failed translation for ID {index}")'

In [ ]:
'''output_path = '/content/drive/MyDrive/Colab Notebooks/train_df_translated.xlsx'
train_df.to_csv(output_path, index=True)'''

"output_path = '/content/drive/MyDrive/Colab Notebooks/train_df_translated.xlsx'\ntrain_df.to_csv(output_path, index=True)"

In [ ]:
train_df_translated = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/train_df_translated (1).xlsx")
train_df_translated

,id,english_text,arabic_reference,Field,Link,english_word_count,arabic_word_count,gpt_translation
0,52,Some Thoughts Concerning Education is a 1693 t...,بعض الأفكار عن التعليم أطروحة كتبها الفيلسوف ...,Education,https://en.wikipedia.org/wiki/Some_Thoughts_Co...,181,166,«بعض الأفكار حول التربية» رسالة صدرت عام 1693 ...
1,36,Emily Wilding Davison (11 October 1872 – 8 Ju...,إميلي وايلدينغ دافيسون (11 أكتوبر 1872 - 8 ي...,Culture and society biographies,https://en.wikipedia.org/wiki/Emily_Davison,219,189,إميلي وايلدينغ دافيسون (11 October 1872 – 8 Ju...
2,119,"The Jarrow March of 5–31 October 1936, also kn...",مسيرة جارو امتدت من 5 حتى 31 أكتوبر عام 1936، ...,History,https://en.wikipedia.org/wiki/Jarrow_March,102,103,مسيرة جارو في الفترة من 5 إلى 31 أكتوبر 1936، ...
3,61,Project Rover was a United States project to d...,كان «مشروع روفر» مشروعًا تابعًا للولايات المتح...,Engineering and technology,https://en.wikipedia.org/wiki/Project_Rover,126,125,كان مشروع روفر مشروعًا أمريكيًا لتطوير صاروخ ن...
4,162,The Analytical Review was an English periodica...,المراجعة التحليلية هي مجلة دورية بريطانية، أسس...,Magazines and comics,https://en.wikipedia.org/wiki/Analytical_Review,59,39,كانت «المراجعة التحليلية» دورية إنجليزية نُشرت...
...,...,...,...,...,...,...,...,...
147,107,The Gurian Republic was an insurgent community...,كانت الجمهورية الغوريانية مجتمعًا متمردًا وُجد...,History,https://en.wikipedia.org/wiki/Gurian_Republic,99,82,كانت جمهورية غوريا كيانًا متمردًا قائمًا بين ع...
148,15,The ghost appeared to claim that Fanny had bee...,ظهر ذلك الشبح ليزعم بأن فاني قد تم تسميمها بما...,Culture and Society,NaN,120,132,ادعى الشبح أن فاني قد سُمِّمت بالزرنيخ، وأُثير...
149,93,"The Birmingham campaign, also known as the Bir...",حملة برمنجهام هي حركة نظمها مؤتمر القيادة المس...,History,https://en.wikipedia.org/wiki/Birmingham_campaign,83,64,حملة برمنغهام، المعروفة أيضًا بحركة برمنغهام أ...
150,180,The Penelopiad is a novella by Canadian author...,بينلوبياد هي رواية للكاتبة مارغريت أتوود تم نش...,"Novels, including graphic novels",https://en.wikipedia.org/wiki/The_Penelopiad,112,93,رواية قصيرة بعنوان «بينيلوبياد» للكاتبة الكندي...
151,103,The Empire of Brazil was a 19th-century state ...,الإمبراطورية البرازيلية، إمبراطورية تأسست عام ...,History,https://en.wikipedia.org/wiki/Empire_of_Brazil,152,140,إمبراطورية البرازيل كانت دولة في القرن التاسع ...

In [ ]:
#we assess the quality of the train test before proceeding with the test set translation and human annotation
subset_df = train_df_translated[:38] #25% of the dataset
subset_df

,id,english_text,arabic_reference,Field,Link,english_word_count,arabic_word_count,gpt_translation
0,52,Some Thoughts Concerning Education is a 1693 t...,بعض الأفكار عن التعليم أطروحة كتبها الفيلسوف ...,Education,https://en.wikipedia.org/wiki/Some_Thoughts_Co...,181,166,«بعض الأفكار حول التربية» رسالة صدرت عام 1693 ...
1,36,Emily Wilding Davison (11 October 1872 – 8 Ju...,إميلي وايلدينغ دافيسون (11 أكتوبر 1872 - 8 ي...,Culture and society biographies,https://en.wikipedia.org/wiki/Emily_Davison,219,189,إميلي وايلدينغ دافيسون (11 October 1872 – 8 Ju...
2,119,"The Jarrow March of 5–31 October 1936, also kn...",مسيرة جارو امتدت من 5 حتى 31 أكتوبر عام 1936، ...,History,https://en.wikipedia.org/wiki/Jarrow_March,102,103,مسيرة جارو في الفترة من 5 إلى 31 أكتوبر 1936، ...
3,61,Project Rover was a United States project to d...,كان «مشروع روفر» مشروعًا تابعًا للولايات المتح...,Engineering and technology,https://en.wikipedia.org/wiki/Project_Rover,126,125,كان مشروع روفر مشروعًا أمريكيًا لتطوير صاروخ ن...
4,162,The Analytical Review was an English periodica...,المراجعة التحليلية هي مجلة دورية بريطانية، أسس...,Magazines and comics,https://en.wikipedia.org/wiki/Analytical_Review,59,39,كانت «المراجعة التحليلية» دورية إنجليزية نُشرت...
5,77,The 1880 United States presidential election w...,كانت الانتخابات الرئاسية في الولايات المتحدة ع...,History,https://en.wikipedia.org/wiki/1880_United_Stat...,46,71,كانت انتخابات الرئاسة الأمريكية لعام 1880 هي ا...
6,70,Icos Corporation (trademark ICOS) was an Ameri...,شركة إيكوس كانت سابقاً شركة أمريكية للتكنولوجي...,Health and medicine,https://en.wikipedia.org/wiki/Icos,101,83,شركة إيكوس (العلامة التجارية ICOS) كانت شركة أ...
7,30,The Whitechapel murders were committed in or n...,جرائم قتل وايت تشابل هي مجموعة من جرائم القتل ...,Culture and Society,https://en.wikipedia.org/wiki/Whitechapel_murders,190,182,وقعت جرائم قتل وايت تشابل في أو بالقرب من حي و...
8,129,Operation Grapple was a set of four series of ...,كانت عملية المرساة اسمًا لأربعة سلاسل اختبار أ...,History,https://en.wikipedia.org/wiki/Operation_Grapple,93,74,كانت عملية غراپل سلسلة مكوَّنة من أربع دفعات م...
9,153,Pilgrim at Tinker Creek is a 1974 nonfiction n...,الحج في خليج (نهر) تنكر هو كتاب سرد عام 1974 ق...,Literature and theatre,https://en.wikipedia.org/wiki/Pilgrim_at_Tinke...,86,80,الحاج في تينكر كريك هو كتاب سردي غير روائي صدر...
10,166,The Bread-Winners: A Social Study is an 1883 n...,المُعيلون هي دراسة اجتماعية في شكل رواية كتبها...,"Novels, including graphic novels",https://en.wikipedia.org/wiki/The_Bread-Winners,49,46,«المعيلون: دراسة اجتماعية» هي رواية صدرت عام 1...
11,32,The World Without Us is a 2007 non-fiction boo...,العالم من دوننا هو كتاب علمي يتناول التوقعات ا...,Culture and Society,https://en.wikipedia.org/wiki/The_World_Withou...,112,161,العالم بدوننا هو كتاب غير روائي صدر عام 2007 ي...
12,154,"All God's Children Need Traveling Shoes, publi...",جميع أطفال الله بحاجة إلى أحذية سفر هو كتاب نُ...,Autobiographies and memoirs,https://en.wikipedia.org/wiki/All_God%27s_Chil...,84,79,كل أولاد الله بحاجة إلى أحذية للسفر، الذي نُشر...
13,13,Constable Hanks reported the matter to his sup...,أبلغ كونستابل هانكس عن الأمر لرؤسائه وأحيلت ال...,Culture and Society,NaN,129,116,أبلغ الشرطي هانكس الأمر إلى رؤسائه وأُحيلت الق...
14,42,"William Hillcourt (August 6, 1900– November 9,...",وليام هيلكورت (6 أغسطس 1900 - 9 نوفمبر 1992)...,Culture and society biographies,https://en.wikipedia.org/wiki/William_Hillcourt,93,80,ويليام هيلكورت (6 أغسطس 1900 – 9 نوفمبر 1992)،...
15,179,Moonraker is the third novel by the British au...,حاصد القمرهي الرواية الثالثة للكاتب البريطاني ...,"Novels, including graphic novels",https://en.wikipedia.org/wiki/Moonraker_(novel),152,131,مون رايكر هي الرواية الثالثة للكاتب البريطاني ...
16,56,A Halkett boat is a type of lightweight inflat...,قارب هاكليت هو نوع من القوارب المطاطية خفيفة ...,Engineering and technology,https://en.wikipedia.org/wiki/Halkett_boat,121,101,زورق هالكيت هو نوع من القوارب القابلة للنفخ وخ...
17,99,Nuclear fission was discovered in December 193...,تم اكتشاف الانشطار النووي في ديسمبر 1938 من قب...,History,https://en.wikipedia.org/wiki/Discovery_of_nuc...,122,84,اُكتُشِفَ الانشطار النووي في ديسمبر 1938 على ي...
18,94,Britain initiated the first research project t...,مساهمة بريطانيا في مشروع مانهاتن بدأت بجهود بذ...,History,https://en.wikipedia.org/wiki/British_contribu...,56,40,بدأت بريطانيا أول مشروع بحثي لتصميم قنبلة ذرية...
19,27,Legends featuring pig-faced women originated r...,نشأت القصص المتعلقة بالنساء ذوات وجه الخنزير ...,Culture and Society,https://en.wikipedia.org/wiki/Pig-faced_women,259,239,نشأت الأساطير التي تتناول نساء بوجوه خنزيرية ت...
20,39,"Sarah Margaret Fuller (May 23, 1810 – July 19,...",سارة مارغريت فولر أوسولي والتي عرفت باسم مارغ...,Culture and society biographies,https://en.wikipedia.org/wiki/Margaret_Fuller,66,68,سارة مارجريت فولر (23 مايو 1810 – 19 يوليو 185...
21,118,The Iranian Embassy siege took place from 30 A...,حدث حصار السفارة الإيرانية في لندن في تاريخ 30...,History,https://en.wikipedia.org/wiki/Iranian_Embassy_...,78,83,جرى حصار سفارة إيران من 30 أبريل إلى 5 مايو 19...
22,157,A Journey is a memoir by Tony Blair of his ten...,كتاب رحلة هو مذكرات توني بلير عن فترة توليه من...,Autobiographies and memoirs,https://en.wikipedia.org/wiki/A_Journey,110,117,«A Journey» مذكرات لتوني بلير عن ولايته كرئيس ...
23,134,The High Middle Ages of Scotland encompass Sco...,العصور الوسطى العليا في اسكتلندا تشمل الفترة ب...,History,https://en.wikipedia.org/wiki/Scotland_in_the_...,179,135,تشمل العصور الوسطى العليا في اسكتلندا الفترة ا...
24,186,Georg Ferdinand Ludwig Philipp Cantor was a ma...,غيورغ فرديناند لودفيغ فيليب كانتور عاش ما بين ...,Biographies of mathematicians,https://en.wikipedia.org/wiki/Georg_Cantor,97,90,جورج فرديناند لودفيج فيليب كانتور كان رياضياتي...
25,140,The Western Chalukya Empire ruled most of the ...,حكمت إمبراطورية تشالوكيا الغربية معظم منطقة غر...,History,https://en.wikipedia.org/wiki/Western_Chalukya...,164,113,حكَمَت إمبراطورية التشالوكيا الغربية معظم غرب ...
26,3,"Harold Adams Innis FRSC (November 5, 1894 – No...",هارولد آدم اينيس (5 نوفمبر 1894- 8 نوفمبر 195...,"Business, economics, and finance biographies",https://en.wikipedia.org/wiki/Harold_Innis,76,87,هارولد آدامز إينيس، زميل الجمعية الملكية في كن...
27,47,"Mary Toft (née Denyer; c. 1701–1763), also spe...",ماري توفت (اسمها قبل الزواج:دانيار، 1701-1763...,Culture and society biographies,https://en.wikipedia.org/wiki/Mary_Toft,112,92,ماري توفت (اسمها قبل الزواج دينير؛ حوالي 1701–...
28,97,The Clinton Engineer Works (CEW) was the produ...,كان كلينتون مهندس أشغال (CEW) اسم منشأة مشروع ...,History,https://en.wikipedia.org/wiki/Clinton_Engineer...,126,101,كانت منشأة مهندسي كلينتون (CEW) هي منشأة الإنت...
29,141,"In early December 1936, a constitutional crisi...",في عام 1936، نشأت أزمة دستورية في الإمبراطورية...,Law,https://en.wikipedia.org/wiki/Abdication_of_Ed...,181,133,في أوائل ديسمبر 1936، نشأت أزمة دستورية في الإ...
30,123,"In the history of Europe, the Middle Ages or m...",العُصُورُ الوسطى أو القُرُونُ الوسطى هي التسمي...,History,https://en.wikipedia.org/wiki/Middle_Ages,88,63,في تاريخ أوروبا، تُعرف العصور الوسطى أو الفترة...
31,37,"Marjory Stoneman Douglas (April 7, 1890 – May ...",مارجوري ستونمان دوغلاس (14 مايو 1998 7 أبريل...,Culture and society biographies,https://en.wikipedia.org/wiki/Marjory_Stoneman...,113,92,مارجوري ستونمان دوغلاس (7 أبريل 1890 – 14 مايو...
32,139,Several failed proposals were made during the ...,كان اتحاد بلغاريا ورومانيا مشروعًا غير ناجح لت...,History,https://en.wikipedia.org/wiki/Union_of_Bulgari...,86,75,طُرحت عدة مقترحات فاشلة خلال القرنين التاسع عش...
33,23,The indigenous people of the Everglades region...,وصل السكان الأصليون لمنطقة إيفرغليدز في شبه جز...,Culture and Society,https://en.wikipedia.org/wiki/Indigenous_peopl...,127,115,وصل السكان الأصليون لمنطقة المستنقعات في شبه ج...
34,116,The Imperial Trans-Antarctic Expedition of 191...,البعثة الإمبراطورية العابرة للقارة القطبية الج...,History,https://en.wikipedia.org/wiki/Imperial_Trans-A...,80,85,تُعتبر حملة الإمبراطورية العابرة للقارة القطبي...
35,83,The Aberfan disaster was the catastrophic coll...,كارثة أبرفان‏ تتمثل بالانهيار الكارثي لطرف منج...,History,https://en.wikipedia.org/wiki/Aberfan_disaster,105,76,كانت كارثة أبرفان انهيارًا كارثيًا لكومة مخلفا...
36,182,Southern Cross is the sole wordless novel by C...,سوثرن كروس أو الصليب الجنوبي هي إحدى الروايات ...,"Novels, including graphic novels",https://en.wikipedia.org/wiki/Southern_Cross_(...,47,47,الصليب الجنوبي هي الرواية الوحيدة بلا كلمات لل...
37,12,"In July 1889, Police Constable Luke Hanks was ...",في يوليو 1889 ، كان ضابط الشرطة لوك هانكس يحقق...,Culture and Society,NaN,171,166,في يوليو 1889، كان مأمور الشرطة لوك هانكس يحقق...

In [ ]:
translations = subset_df['gpt_translation'].tolist()
references = subset_df['arabic_reference'].tolist()
references

[' بعض الأفكار عن التعليم أطروحة كتبها الفيلسوف الإنجليزي جون لوك عام 1693 يناقش فيها «تعليم الفئة النبيلة». وقد ظلت هذه الأطروحة أهم الأعمال الفلسفية عن التعليم في إنجلترا لأكثر من قرن، وتُرجمت خلال القرن الثامن عشر إلى جميع اللغات الأوروبية المكتوبة الرئيسية تقريبًا، كما اعترف بتأثيرها البالغ الكتاب الأوروبيون الذين تناولوا موضوع التعليم بعد لوك، بمن فيهم جان جاك روسو. \nوفي مقالته التي تسمى «مقال عن الفهم الإنساني» الذي كُتب في عام 1690، ابتكر لوك نظرية عقلية جديدة، تؤمن النظرية بأن العقل عند مولد الإنسان وقبل تعلمه مثل الصفحة البيضاء، فهو لا يولد بأي أفكار فطرية أو غريزية. وفي «بعض الأفكار عن التعليم» يوضح لوك ثلاث طرق لتعليم هذا العقل وهم: تنمية جسد صحي والمحافظة عليه، تربية شخصية تتميز بالأخلاق الحميدة، واختيار مناهج دراسي مناسبة. \nفي البداية، كتب لوك هذا المقال على هيئة رسائل يبعثها لصديق له من الطبقة الأرسطوقراطية، ولكن نصائحه حازت على الرضى والإعجاب بسبب قيمه التعليمية التي سمحت للسيدات والطبقات الفقيرة بالارتفاع ليتساوو بالارسطوقراطيين الذي، في الأصل، كتب لوك هذا الكتاب من اجلهم. ',
 ' إميلي وايلدينغ دافيسون  (11 أكتوبر 1872 - 8 يونيو 1913) كانت ناشطة في حق تصويت المرأة الإنجليزية، حاربت من أجل حق النساء في التصويت في بريطانيا في أوائل القرن العشرين. كانت عضوًا في الاتحاد الاجتماعي والسياسي للمرأة ومناضلة أجل قضيتها، قُبض عليها تسع مرات، وأضربت عن الطعام سبع مرات وأُطعمت قسرًا تسع وأربعين مرة. توفيت بعد أن ضربها حصان الملك جورج الخامس أنمر في ديربي عام 1913 عندما دخلت إلى المضمار خلال السباق. \nنشأت دافيسون في عائلة من الطبقة المتوسطة، ودرست في كلية رويال هولواي، جامعة لندن، وكلية سانت هيو، جامعة أكسفورد، قبل توليها وظائف كمدرسة ومربية. انضمت إلى الاتحاد الاجتماعي والسياسي للمرأة في نوفمبر عام 1906 وأصبحت ضابطة في المنظمة وقائدة خلال المسيرات. سرعان ما أصبحت معروفة في المنظمة لعملها الجريء المتشدد. تضمنت أساليبها تحطيم النوافذ، ورمي الحجارة، وإشعال النار في صناديق البريد، وفي ثلاث مرات، الاختباء طوال الليل في قصر وستمنستر -بما في ذلك ليلة التعداد السكاني عام 1911. نظم الاتحاد الاجتماعي والسياسي للمرأة جنازتها في 14 يونيو عام 1913. \nرافق موكب مكون من 5000 ناشط في حق تصويت المرأة ومؤيديهم تابوتها واصطف 50,000 شخص على طرقات لندن؛ نُقل نعشها بالقطار إلى منزل الأسرة في موربيث، نورثمبرلاند. ',
 'مسيرة جارو امتدت من 5 حتى 31 أكتوبر عام 1936، وتُعرف أيضًا باسم حملة جارو الصليبية، وهي احتجاج منظم ضد البطالة والفقر اللذين عانت منهما مدينة جارو الإنجليزية خلال الثلاثينيات من القرن العشرين. وقد سار نحو 200 رجل (أو «صليبي» كما كانوا يفضلون تلقيب أنفسهم) في مسيرة من جارو إلى لندن، حاملين التماسًا إلى الحكومة البريطانية يطلبون فيه إعادة إحياء الصناعة في المدينة بعد إغلاق مكان العمل الرئيسي، وهو حوض بالمر لبناء السفن في عام 1934. وجرى استلام الالتماس من قبل مجلس العموم ولكنه لم يناقش، وكان للمسيرة نتائج فورية قليلة. وعاد أهل مدينة جارو إلى منازلهم وهم يعتقدون أنهم فشلوا في مسعاهم.',
 'كان «مشروع روفر» مشروعًا تابعًا للولايات المتحدة يهدف لتطوير صاروخ نووي حراري استمر بين عامي 1955 و1973 في مختبر «لوس ألاموس» العلمي (إل إيه إس إل). بدأ كمشروع للقوات الجوية الأمريكية لتطوير مرحلة صاروخية عليا تعمل بالطاقة النووية لصاروخ باليستي عابر للقارات (آي سي بي إم). نُقل المشروع إلى وكالة ناسا في عام 1958 بعد أن تسببت أزمة «سبوتنيك» في بدء سباق الفضاء. وقد أداره مكتب الدفع النووي الفضائي (إس إن بّي أوه)، وهي وكالة مشتركة بين لجنة الطاقة الذرية (إيه إي سي) ووكالة ناسا. أصبح مشروع روفر جزءًا من مشروع المحرك النووي للمركبات الصاروخية (نيرفا) التابع لناسا، ومن ذلك الوقت فصاعدًا، تناول مشروع روفر البحث في تصميم مفاعل صاروخي نووي، بينما انشغل مشروع نيرفا في التطوير الشامل لمحركات الصواريخ النووية ونشرها، والتخطيط للمهمات الفضائية.',
 'المراجعة التحليلية هي مجلة دورية بريطانية، أسسها جوزيف جونسون والكاتب توماس كريستي، وكانت تصدر في لندن، في الفترة ما بين عام 1788 حتى العام 1798، قدمت ملخصات وتحليلات للعديد من المنشورات الجديدة التي صدرت في نهاية القرن الثامن عشر.',
 'كانت الانتخابات الرئاسية في الولايات المتحدة عام 1880م هي الانتخابات الرئاسية ال24 التي تتكرر كل أربع سنوات، التي عقدت يوم الثلاثاء الموافق 2 نوفمبر عام 1880م. واعتبرت إلى حد كبير على أنها استفتاء على نهاية إعادة الإعمار في الولايات الجنوبية قامت بها الجمهوريون. لم تكن هناك قضايا أخرى ملحة يومًا ما عدا سياسة التعريفة الجمركية خاصة مع الجمهوريين والذن دعموا ارتفاع الرسوم الجمركية على عكس الديمقراطيين الذين هم أقل دعمًا منهم.',
 'شركة إيكوس كانت سابقاً شركة أمريكية للتكنولوجيا الحيوية وأكبر شركة للتكنولوجيا الحيوية في ولاية واشنطن الأمريكية، ثم في عام 2007 تم بيعها لشركة إيلي ليلي وشركاه. قام كل من ديفيد بليش، وإسحاق بليش، وروبرت نوينسكي وجورج راثمان بتأسيسها عام 1989. ركز إيكوس على تطوير الأدوية لعلاج الاضطرابات الالتهابية. وخلال تاريخها الممتد لـ 17 عاماً، أجرت الشركة تجارب سريرية على اثني عشر دواءً، وصلت ثلاثة منها إلى المرحلة الأخيرة من التجارب السريرية. قامت شركة إيكوس أيضًا بتصنيع الأجسام المضادة لشركات التكنولوجيا الحيوية الأخرى.   \n\n \u200f ',
 'جرائم قتل وايت تشابل هي مجموعة من جرائم القتل التي ارتكبت في منطقة وايت تشابل الفقيرة أو بالقرب منها، وهي تقع في الطرف الشرقي من لندن، وقد وقعت هذه الجرائم في ما بين 3 أبريل 1888 و13 فبراير 1891 م، وعددها إحدى عشرة جريمة. بعض هذه الجرائم الإحدى عشرة أو كلها تُنسب إلى القاتل المتسلسل المجهول المعروف باسم "جاك السفاح"، وقد ارتكبت هذه الجرائم على النساء. \nمعظم الضحايا، إن لم يكن كلهن، وهن: إيما إليزابيث سميث، مارثا تابرام، ماري آن نيكولز، آني تشابمان، إليزابيث سترايد، كاثرين أيدوس، ماري جين كيلي، روز مايليت، أليس ماكنزي، فرانسيس كولز، وواحدة مجهولة الهوية، كنَّ مومسات. اعتدت عصابة على سميث جنسياً وقامت بسرقتها، وطُعنت تابرام 39 طعنة، وأما نيكولز، وتشابمان، وسترايد، وأيدوس، وكيلي، وماكنزي، وكولز، فقد قُطعت حناجرهم. قُتلت أيدوس وسترايد في نفس الليلة، وكان يفصل بينهما دقائق وأقل من ميل واحد، ولُقبت جريمتيهما بلقب "الحدث المزدوج"، وذلك بعد عبارة وردت في بطاقة بريدية أرسلها إلى الصحافة شخص يدعي أنه جاك السفاح. كان على جثث نيكولز، وتشابمان، وأيدوس، وكيلي تشويهات في البطن، وخُنقت مايليت خنقاً، وأما المرأة المجهولة فقد فُكك جسمها، ولكن السبب الدقيق لوفاتها غير واضح. ',
 'كانت عملية المرساة اسمًا لأربعة سلاسل اختبار أسلحة نووية بريطانية لأول القنابل الذرية والهيدروجينية، التي نُفذت بين عامي 1957 و1958 في كل من جزيرتي مالدن وكريماتي (جزيرة عيد الميلاد) في المحيط الهادئ كجزء من البرنامج البريطاني للقنبلة الهيدروجينية. أجريت تسع تفجيرات نووية، توّجت بتحول المملكة المتحدة إلى ثالث دولة معترف بامتلاكها أسلحة نووية حرارية، وباستعادة العلاقة النووية الخاصة التي تربطها بالولايات المتحدة عبر اتفاقية الدفاع المشترك بين الولايات المتحدة والمملكة المتحدة في عام 1958.',
 'الحج في خليج (نهر) تنكر هو كتاب سرد عام 1974 قصصي للمؤلف الأميركي آني ديلارد. وقال من وجهة نظر الشخص الأول للعرض، تفاصيل كتاب الاستكشافات والراوي المجهول، بالقرب من منزلها، والتأملات المختلفة على الطبيعة والحياة. عنوان يشير إلى نهر تنكر، الذي هو خارج رونوك في جبال بلو ريدج في ولاية فرجينيا. \nبدأت ديلارد كتابة الحج في ربيع عام 1973، وذلك باستخدام المجلات الشخصية والإلهام.تم تقسيم الكتاب إلى أربعة أقسام التي تدل على كل المواسم، والسرد يحدث خلال فترة سنة واحدة. ',
 'المُعيلون هي دراسة اجتماعية في شكل رواية كتبها جون هاي صدرت عام 1883. كان جون هاي سكرتيرًا سابقًا للرئيس الأمريكي أبراهام لينكولن وشغل منصب وزير الخارجية عام 1898. تقوم فكرة الكتاب على مناهضة العمل المنظم وأثار عند نشره ضجة واسعة بين صفوف الجماهير لمعرفة هوية مؤلفه.',
 'العالم من دوننا هو كتاب علمي يتناول التوقعات المحتملة التي يمكن أن تصيب البيئة المشيدة والبيئة الطبيعية عند اختفاء البشر. مؤلف الكتاب هو الصحفي الأمريكي آلان فايسمان، وقد تم نشر الكتاب من خلال دار توماس دن للكتب في عام 2007. حاز الكتاب على جائزة أفضل الكتب المسموعة من مجلة أوديو فايل، وجائزة الاستماع من دار الناشرين الأسبوعية، وجائزة دائرة الكتاب النقاد الوطنية النهائية من دائرة الكتاب النقاد الوطنية، وجائزة الكتب الملحوظة للكبار عن مجلس الكتب الملحوظة. \nيعتبر العمل نسخة موسعة من مقال الأرض من دون البشر لنفس المؤلف والذي تم نشره في مجلة ديسكفر في فبراير من عام 2005. كتب المؤلف على سبيل التجربة ملخص للكتاب، فأشار إلى شكل المدن والمنازل وهي تتدمر، وكم هي الآثار الصناعية التي ستقاوم وتبقى سائدة، وكيف ستتطور أشكال الحياة المتبقية. يستنتج فايسمان أن الأحياء السكنية ستتحول إلى غابات خلال مدة لا تتجاوز خمسمائة عام، وأن النفايات الملوثة بالإشعاع والتماثيل البرونزية والبلاستيك وكذلك جبل راشمور ستظل من بين الأدلة الأكثر دوامًا لوجود الإنسان على كوكب الأرض. ',
 'جميع أطفال الله بحاجة إلى أحذية سفر هو كتاب نُشر في عام 1986، وهو الكتاب الخامس في سلسلة السيرة الذاتية للشاعرة مايا أنجيلو، المؤلفة من سبعة مجلدات. يبدأ الكتاب بين عامي 1962 و1965 عندما بلغت أنجيلو عامها الثالث الثلاثون، وفيه تروي أنجيلو السنوات التي عاشت فيها في أكرا في غانا. اشتُقّ عنوان الكتاب من أغاني روحانية زنجية. يبدأ الكتاب حيث انتهت مذكرات أنجيلو السابقة «قلب امرأة» -بحادث سيارة مؤلم تعرض له ابنها غاي- وينتهي مع عودة أنجيلو إلى أمريكا.',
 'أبلغ كونستابل هانكس عن الأمر لرؤسائه وأحيلت القضية إلى المحقق المفتش فريدريك أبيرلين . ذهب المفتش ابإلى بيت الدعارة في 6 يوليو بأمر اعتقال هاموند ونيولوف لانتهاكه المادة 11 من قانون تعديل القانون الجنائي لعام 1885 . ونص القانون على أن جميع الأفعال المثلية بين الرجال ، وكذلك القوادة أو الشروع في مثل هذه الأفعال ، يعاقب عليها بالسجن لمدة تصل إلى سنتين مع الأشغال الشاقة أو بدونها. وجد المنزل مغلقًا وذهب هاموند ، لكن أببرلين كان قادرًا على القبض على حب جديد في منزل والدته في كامدن تاون . في الفترة الفاصلة بين بيانه أمام هانكس واعتقاله ، ذهب نيولوف إلى شارع كليفلاند وحذر هاموند ، الذي هرب بالتالي إلى منزل شقيقه في جرافيسند .',
 ' وليام هيلكورت  (6 أغسطس 1900 - 9 نوفمبر 1992) والمعروف داخل الحركة الكشفية بأنه " بار بيل الأخضر"، كان قائداً مؤثراً في منظمة الكشافة الأمريكية (Boy Scouts of America ) من 1927 إلى 1992. كان هيلكورت كاتباً كثير الكتابة ومعلماً في مجالات النحت على الخشب، وفي بنية الفرق والدوريات، وأيضاً التدريب؛ وتشمل أعماله المكتوبة ثلاثة نسخ من دليل الكشافة الرسمي للولايات المتحدة الأمريكية، مع أكثر من 12.6 مليون نسخة مطبوعة، وغيرها من الكتب ذات الصلة بالكشافة والعديد من مقالات المجلات. ',
 'حاصد القمرهي الرواية الثالثة للكاتب البريطاني إيان فلمنغ التي تصور عميله الخيالي جيمس بوند في جهاز الخدمة السرية البريطانية. نشرت دار جوناثان كيب الرواية في 5 أبريل 1955 وكان تصميم غلاف الرواية من فكرة فلمنغ. اشتُقت الحبكة من سيناريو قصير جدًا كتبه فلمنغ لرواية كاملة، لذلك أضاف إليها لعبة البريدج بين بوند ورجل الصناعة هوغو دراكس . ينضم بوند إلى طاقم دراكس في النصف الأخير من الرواية، حيث يبني رجل الأعمال نموذج حاصد القمر، النموذج الأولي لصاروخ مصمم للدفاع عن إنجلترا. كان بوند يجهل أصل دراكس، وهو ألماني ونازي سابق كان يعمل حينها لصالح السوفيت. وقد تضمنت مكيدته إعداد صاروخ وتسليحه برأس نووي وإطلاقه تجاه لندن. صوُر فيلم حاصد القمر في بريطانيا بالكامل وهو أمر فريد بالنسبة لروايات بوند، مما أثار استياء بعض القراء الذين شكوا من نقص وجود الأماكن الغريبة. \n\n ',
 ' قارب هاكليت هو نوع من القوارب المطاطية خفيفة الوزن والذي صممه الملازم بيتر هالكيت (1820–1885) في أربعينيات القرن التاسع عشر. كان هالكيت مهتماً لفترة طويلة بصعوبات السفر والتنقل في شمال كندا، وكان ضمن هذه الاهتمامات تصميم قارب خفيف بشكل يناسب التضاريس والطرق الوعرة ومع ذلك يكون قوي كفاية حتى يقدر على التصدي لتغيرات المناخ الحادة. \nتصميم هالكيت الأول كان مطاطياً، قابلاً للطي ومصنوعاً من القماش المُشرب بالمطاط وعند طي هذا القارب يمكن استخدام هيكله كمعطف، والمجداف كعصا للمشي والشراع كمظلة. وهذا كان متبوعاً بمركب صغير يتسع لرجُلين والذي كان صغيراً كفاية لأن تسعه حقيبة ظهر، وعند طيه يُستخدم كبطانية مضادة للماء. \n\n ',
 'تم اكتشاف الانشطار النووي في ديسمبر 1938 من قبل الفيزيائيين ليز مايتنر وأوتو روبرت فريش والكيميائيين أوتو هان وفريتز شتراسمان. الانشطار هو تفاعل نووي أو عملية تحلل إشعاعي تنقسم فيها نواة الذرة إلى نواتين أصغر حجمًا وأخف وزنًا. غالبًا ما تنتج عملية الانشطار أشعة جاما وتطلق كمية كبيرة جدًا من الطاقة، حتى بالمعايير النشطة للانحلال الإشعاعي. كان العلماء يعرفون بالفعل عن تسوس ألفا واضمحلال بيتا، لكن الانشطار اكتسب أهمية كبيرة لأن اكتشاف إمكانية حدوث تفاعل نووي متسلسل أدى إلى تطوير الطاقة النووية والأسلحة النووية.',
 'مساهمة بريطانيا في مشروع مانهاتن بدأت بجهود بذلت وأبحاث قدمت للولايات المتحدة بهدف المساعدة على تطوير أول قنابل ذرية في الولايات المتحدة خلال الحرب العالمية الثانية، وكانت بريطانيا قد ساعدت في استكماله حتى الانتهاء في أغسطس 1945 بتقديمها لخبرة اللازمة.',
 ' نشأت القصص المتعلقة بالنساء ذوات وجه الخنزير في هولاندا، وإنجلترا، وفرنسا في نفس الوقت تقريبًا وذلك في أواخر الثلاثينيات من القرن السابع عشر. تحكي تلك القصص عن امرأة ثرية لها جسد بشري ولكن وجهها وجه خنزير. \nفي باديء ذي بدء كان السحر هو السبب وراء امتلاك هذه المرأة لوجه الخنزير. وعقب يوم زفافها مُنح زوجها حق الاختيار ما بين أن تكون جميلة في نظره وبذلك تظل كما هي في نظر الآخرين أو العكس. ولكن عندما أخبرها زوجها أنها هي من تملك حق الاختيار، انفك السحر واختفى وجه الخنزير. وانتشرت تلك القصص في إنجلترا على وجه الخصوص وفي أيرلاندا فيما بعد. \nولكن بعد ذلك اختفى تدريجيا عنصر السحر من القصة، وبدأ الناس يتعاملون مع وجود هؤلاء النساء كحقيقة. وانتشرت تلك القصة على وجه الخصوص في دبلن في بداية القرن التاسع عشر، حيث سادت فكرة أن غريسيلدا ستيفنز، وهي فاعلة خير منطوية كانت تعيش في القرن الثامن عشر، أخفت نفسها عن الأنظار لأن لها وجه خنزير. وفي أواخر عام 1814 وأوائل عام 1815 اكتسحت شائعة لندن بأن امراة ذات وجه خنزير تعيش في مدينة مارليبون. وأشارت العديد من المقالات إلى وجود هذه المرأة حقًا ونُشرت لها العديد من الصورالمدعية. ومع شيوع التصديق بوجود ذلك النوع من النساء، عرض مخرجوا الاستعراض غير الأمناء مشاهد لهن في عروضهم. ولكن لم يكن الممثلون نساء حقًا، إنما كانوا رجال متنكرين في زي النساء. \nضعُف بعد ذلك التصديق بوجود هؤلاء النساء، وكان آخر عمل جَدي يعالج وجودهن نشر عام 1924. أما الآن فقد تلاشت هذه الأسطورة. \n\n ',
 'سارة مارغريت فولر أوسولي  والتي عرفت باسم مارغريت فولر ناقدة أدبية وصحفية، وُلدت في 23 مايو عام 1810. وتوفيت في 19 يوليو عام 1850. كانت فولر ناقدة أدبية وصحفية أمريكية ومدافعة عن حقوق المرأة والذي أَقترن بحركات المرأة الأمريكية. كما كانت أول امرأة أمريكية تشتغل بالنقد الأدبي في مجال الصحافة. يعتبر كتابها المرأة في القرن التاسع عشر من أهم أوائل الأعمال في مجال النسوية في الولايات المتحدة الأمريكية.',
 'حدث حصار السفارة الإيرانية في لندن في تاريخ 30 أبريل إلى 5 مايو عام 1980م، عندما اقتحم ستة مسلحون من الجبهة العربية لتحرير الأحواز مبني السفارة الإيرانية في لندن في ساوث كنزنغتون واحتجزوا 26 رهينة. وقد هددوا بقتلهم إن لم تسلم بريطانيا 91 سجينًا سياسيا من عرب أحوازيين في السجون الإيرانية، كما طلبوا من سفراء الدول العربية التوسط مع إيران ومن أجل السيادة الوطنية العربية في منطقة خوزستان الجنوبية الإيرانية، إلا أن رئيسة الوزراء البريطانية مارغريت ثاتشر أمرت بتنفيذ عملية عسكرية لتحرير الرهائن.',
 'كتاب رحلة هو مذكرات توني بلير عن فترة توليه منصب رئيس وزراء المملكة المتحدة حيث نُشر هذا الكتاب بتاريخ الأول من أيلول/سبتمبر 2010م. ويشمل هذا الكتاب الأحداث بدءًا من تولي بلير زعامة حزب العمال في عام 1994م، ودوره في تحويل الحزب إلى حزب العمال الجديد، بالإضافة إلى الرقم القياسي لتوليه إدارة الحزب ثلاث مرات متتالية، حتى استقالته وتعيينه رئيسًا للوزراء وحل محله جوردون براون، وزير الخزانة البريطاني. كما تبرع بلير بمبلغ تصل قيمته 4.6 مليون جنيه استرليني مقدم مخصصاته الملكية، بالإضافة إلى كل مخصصاته الملكية التالية إلى القوات المسلحة البريطانية أو مايعرف باسم الفيلق الملكي البريطاني. وأصبحت سيرته الذاتية هي الأسرع مبيعًا في كل العصور ضمن سلسلة مكتبة ووترستونز. كما أتسمت الأحداث الترويجية لها باحتجاجات مناهضة للحرب.',
 'العصور الوسطى العليا في اسكتلندا تشمل الفترة بين وفاة دومنال الثاني في عام 900 ووفاة الملك ألكسندر الثالث في عام 1286، والتي كانت سببًا غير مباشر لحروب الاستقلال الاسكتلندية. في نهاية القرن التاسع، احتلت الممالك المتنافسة المختلفة أراضي اسكتلندا الحديثة. كان التأثير الإسكندنافي طاغيًا في الجزر الشمالية والغربية، والثقافة البريتونية في الجنوب الغربي، أو المملكة الأنجلوسكسونية أو مملكة نورثمبريا الإنجليزية في الجنوب الشرقي، ومملكة ألبا البكتية والغيلية في الشرق، شمال نهر فورث. في القرنين العاشر والحادي عشر، هيمنت الثقافة الغيلية على شمال بريطانيا العظمى بشكل متزايد، ومن قِبل مملكة ألبا الغيلية، والمعروفة باللاتينية باسم ألبانيا أو سكوتيا، وبالإنجليزية باسم «اسكتلندا». من قاعدتها في الشرق، تمكنت هذه المملكة من السيطرة على الأراضي الواقعة في الجنوب، وأخيرًا في الغرب والشمال. كانت لديها ثقافة مزدهرة، مشكّلةً جزءًا من العالم الأكبر الناطق باللغة الغيلية واقتصادًا تهيمن عليه الزراعة والتجارة.',
 'غيورغ فرديناند لودفيغ فيليب كانتور عاش ما بين 3 مارس 1845 - 6 يناير 1918م عالم رياضيات ألماني يشار إليه بأنه واضع نظرية المجموعات الحديثة ويعتبر أول من أشار إلى أهمية مبدأ التقابل واحد لواحد بين المجموعات، ومن عرف المجموعات اللامنتهية والمجموعات جيدة الترتيب ، كما أنه أثبت أن الأعداد الحقيقية أكثر بكثير من الأعداد الطبيعية. وفي الواقع فإن نظرية كانتور تستلزم وجود عدد غير منته من المالانهايات. وكذلك فإن كانتور هو من عرف أعداد الكمية واعداد الرتبة وطرق الحساب الخاصة بها. ويعرف عن أعماله أنها ذات قيمة فلسفية عالية.\n ',
 'حكمت إمبراطورية تشالوكيا الغربية معظم منطقة غرب ديكان في جنوب الهند في الفترة الممتدة بين القرنين العاشر والثاني عشر. تسمى سلالة الكناديجا أحيانًا باسم كالياني تشالوكيا بعد أن جعلوا من مدينة كالياني عاصمةً لهم، في حين يُطلق على السلالة التي حكمت الجزء الغربي من الإمبراطورية اسم تشالوكيا تمييزًا لهم عن السلالة السابقة. \nسيطرت إمبراطورية راشتراكوتا على معظم منطقة ديكان ووسط الهند لمدة قرنين تقريبًا قبل ظهور سلالة تشالوكيا. دبَّت الفوضى في إمبراطورية راشتراكوتا في عام 973 بعد غزوٍ ناجح لعاصمتهم قام به تايلابا الثاني حاكم سلالة بارامارا، وهو ما سهل مهمة سيطرة سلالة تشالوكيا على حكم إمبراطورية راشتراكوتا. تحولت تشالوكيا إلى إمبراطورية تحت حكم سوميشفارا الأول الذي نقل العاصمة من مانيكيتا إلى كالياني. ',
 ' هارولد آدم اينيس (5 نوفمبر 1894- 8 نوفمبر 1952) أستاذ كندي في علم الاقتصاد السياسي في جامعة تورونتو ومؤلف أعمال أساسية عدة في الإعلام ونظرية الاتصال والتاريخ الاقتصادي الكندي. سُميت الكلية التابعة لجامعة تورنتو «اينيس» تيمناً به. على الرغم من صعوبة وكثافة نثره، إلا أن الدارسين يعتبرونه واحد من أكثر مفكرين كندا أصالة. ولقد ساعد في تطوير فرضية المواد الغذائية والتي تفترض أن ثقافة كندا وتاريخها السياسى والاقتصادي قد تأثروا بصورة حاسمة بإستثمار وتصدير مجموعة من السلع الرئيسية مثل الفرو والسمك والخشب والقمح والمعادن المنجمية والوقود الأحفوري. \n',
 ' ماري توفت (اسمها قبل الزواج:دانيار، 1701-1763)، أيضا يتهجى "توفتس"، كانت امرأة إنجليزية من جودالمينج بمقاطعة سري، في عام 1726 أثارت جدلا كبيرا لأنها خدعت الأطباء وجعلتهم يصدقون أنها أنجبت أرانب. \nفي عام 1726 كانت توفت حامل، ورأت في الحلم أنها ستلد أرنب لذلك أُجهضت. وادعاءها بأنها أنجبت أجزاء من حيوانات مختلفة دفعت إلى قدوم الجراح المحلي جون هوارد الذي حقق في تلك المسألة، تلقى بعض من أجزاء لحم الحيوان وبناءا على ذلك قام بإخطار الأطباء البارزين الذين جذبوا الأنتباه لتلك القضية سانت أندريه جراح الأسرة الملكية للملك جورج الأول ملك بريطانيا العظمى. \n\n \n\n ',
 'كان كلينتون مهندس أشغال (CEW) اسم منشأة مشروع مانهاتن ومرفق الإنتاج خلال الحرب العالمية الثانية التي أنتجت اليورانيوم المخصب الذي أستخدم في قصف هيروشيما في أغسطس 1945. ويتألف من مرافق الإنتاج، والمرافق، وبلدة أوك ريدج. وكان في الجزء الشرقي من ولاية تينيسي، حوالي 18 ميل (29 كـم) غرب نوكسفيل، وكان اسمه بعد مدينة كلينتون (تينيسي)، ثمانية ميل (13 كـم) إلى الشمال. وكانت مرافق الإنتاج بشكل رئيسي في رون كاونتي على الرغم من أن الجزء الشمالي من الموقع كان في مقاطعة أندرسون. المهندس حي مانهاتن، كينيث ديفيد "نيك" نيكولز، قد نقل مقر منطقة مانهاتن من مانهاتن إلى أوك ريدج في أغسطس 1943. ',
 'في عام 1936، نشأت أزمة دستورية في الإمبراطورية البريطانية عندما اعتزم الملك الإمبراطور إدوارد الثامن الزواج من واليس سيمبسون، وهي امرأة أمريكية بارزة اجتماعيًا انفصلت عن زوجها الأول وكانت تسعى في طلاق زوجها الثاني. \nعارضت حكومات المملكة المتحدة ودول دومينيون الكومنولث البريطاني زواجهما. أُثيرت اعتراضات دينية وقانونية وسياسية وأخلاقية. بصفته العاهل البريطاني، كان إدوارد الرئيس الاسمي لكنيسة إنجلترا، التي لم تسمح في ذلك الوقت للمطلقين بالزواج مرة أخرى في الكنيسة إذا كان أزواجهم السابقون على قيد الحياة. لهذا السبب، شاع الاعتقاد بأن إدوارد لا يمكنه الزواج بسيمبسون والبقاء على العرش. تداول العديد آراءً تفيد بعدم أهلية سيمبسون سياسيًا واجتماعيًا كملكة قرينة مستقبلية بسبب زواجيها السابقين. افترضت المؤسسة الحاكمة عمومًا أن سيمبسون كانت مدفوعة بحب المال أو المنصب وليس حب الملك. رغم المعارضة، أعلن إدوارد حبه لسيمبسون ونيته الزواج بها بمجرد استكمال طلاقها الثاني. ',
 'العُصُورُ الوسطى أو القُرُونُ الوسطى هي التسمية التي تُطلق على الفترة الزمنية في التاريخ الأوروبي التي امتّدت من القرن الخامس حتّى القرن الخامس عشر الميلادي. حيث بدأت بانهيار الإمبراطورية الرومانية الغربية واستمرّت حتى عصر النهضة والاستكشاف. وتُعتبر فترة العصور الوسطى هي الفترة الثانية بين التقسيمات التقليدية للتاريخ الغربي: الفترة القديمة، والوسطى، والحديثة. وتنقسم العصور الوسطى نفسها إلى ثلاثة فَترات: الفترة المُبكّرة، والمتوسّطة، والمُتأخّرة.',

In [ ]:
# Compute overall BLEU
bleu = BLEU()
bleu_score = bleu.corpus_score(translations, [references]).score
print(f"Overall BLEU score for subset: {bleu_score:.2f}")

Overall BLEU score for subset: 18.84

In [ ]:
data = [
    {"src": row['english_text'], "mt": row['gpt_translation'], "ref": row['arabic_reference']}
    for _, row in subset_df.iterrows()
]

In [ ]:
model_path = download_model("Unbabel/wmt22-comet-da")
model = load_from_checkpoint(model_path)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:104: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(

Fetching 5 files:   0%|          | 0/5 [00:00<?, ?it/s]

hparams.yaml:   0%|          | 0.00/567 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

LICENSE: 0.00B [00:00, ?B/s]

.gitattributes: 0.00B [00:00, ?B/s]

checkpoints/model.ckpt:   0%|          | 0.00/2.32G [00:00<?, ?B/s]

INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.8.3.post1 to v2.5.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../root/.cache/huggingface/hub/models--Unbabel--wmt22-comet-da/snapshots/2760a223ac957f30acfb18c8aa649b01cf1d75f2/checkpoints/model.ckpt`

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.10M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/616 [00:00<?, ?B/s]

/usr/local/lib/python3.12/dist-packages/pytorch_lightning/core/saving.py:195: Found keys that are not in the model state dict but in the checkpoint: ['encoder.model.embeddings.position_ids']

In [ ]:
comet_scores = model.predict(data, batch_size=8, gpus=0)

INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: False, used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 5/5 [04:54<00:00, 58.89s/it]

In [ ]:
print(f"Overall COMET score for subset: {comet_scores.system_score:.4f}")

Overall COMET score for subset: 0.8579

In [ ]:
#save subset_df as excel sheet for annotators scoring
subset_df.to_excel('/content/drive/MyDrive/Colab Notebooks/subset_df.xlsx', index=False)

In [ ]:
test_df

,english_text,arabic_reference,Field,Link,english_word_count,arabic_word_count,gpt_translation
id,,,,,,,
176,The Historian is the 2005 debut novel of Ameri...,هي الرواية الأولى للكاتبة الأمريكية إليزابيث ك...,"Novels, including graphic novels",https://en.wikipedia.org/wiki/The_Historian,81,79,NaN
181,The Phantom Tollbooth is a children's fantasy ...,المحصل فانتوم هي رواية مغامرات خيالية للأطفال ...,"Novels, including graphic novels",https://en.wikipedia.org/wiki/The_Phantom_Toll...,107,95,NaN
112,"Solidarity, a Polish non-governmental trade un...",حركة تضامن هي نقابة عمالية غير حكومية أسسها لي...,History,https://en.wikipedia.org/wiki/History_of_Solid...,70,65,NaN
66,The Sholes and Glidden typewriter (also known ...,آلة شولز وغلايدن الكاتبة هي أول الآلات الكاتبة...,Engineering and technology,https://en.wikipedia.org/wiki/Sholes_and_Glidd...,115,90,NaN
102,"On 9 February 2001, about nine nautical miles ...",في 9 فبراير 2001 اصطدمت الغواصة يو إس إس غرينف...,History,https://en.wikipedia.org/wiki/Ehime_Maru_and_U...,99,82,NaN
16,The Cottingley Fairies appear in a series of f...,تظهر جنيات كوتينجلي في سلسلة من خمس صور التقط...,Culture and Society,https://en.wikipedia.org/wiki/Cottingley_Fairies,196,169,NaN
10,The Burke and Hare murders were a series of si...,ارتكب بورك وهير 16 جريمة قتل موزعة على فترات ا...,Culture and Society,https://en.wikipedia.org/wiki/Burke_and_Hare_m...,236,264,NaN
17,Mark Saunders was a British barrister who was ...,كان مارك سوندرز محاميًا بريطانيًا حين قُتل برص...,Culture and Society,https://en.wikipedia.org/wiki/Death_of_Mark_Sa...,180,182,NaN
142,The Coinage Act of 1873 or Mint Act of 1873 wa...,كان قانون سك العملة لعام 1873 أو قانون العملات...,Law,https://en.wikipedia.org/wiki/Coinage_Act_of_1...,100,82,NaN
125,"The murder of Julia Martha Thomas, dubbed the ...",إن مقتل جوليا مارثا توماس ، يطلق عليه اسم لغز ...,History,https://en.wikipedia.org/wiki/Murder_of_Julia_...,142,138,NaN
110,The history of Lithuania between 1219 and 1295...,يوثّق تاريخ ليتوانيا بين عامي 1219 و1295 تأسيس...,History,https://en.wikipedia.org/wiki/History_of_Lithu...,135,109,NaN
96,"The Palace of Westminster, the medieval royal ...",حريق البرلمان هو حريق اندلع في 16 أكتوبر 1834...,History,https://en.wikipedia.org/wiki/Burning_of_Parli...,90,72,NaN
19,Disco Demolition Night was a Major League Base...,كانت ليلة هدم ديسكو عبارة عن عرض ترويجي لدوري...,Culture and Society,https://en.wikipedia.org/wiki/Disco_Demolition...,105,86,NaN
165,Wonder Stories was an early American science f...,قصص العجائب هي مجلة خيال علمي أمريكية قديمة تم...,Magazines and comics,https://en.wikipedia.org/wiki/Wonder_Stories,70,66,NaN
86,"Alodia, also known as Alwa, was a medieval kin...",مملكة علوة، وتعرف أيضًا باسم ألوديا، هي مملكة ...,History,https://en.wikipedia.org/wiki/Alodia,171,160,NaN
121,"Macedonia, also called Macedon, was an ancient...",كانت مقدونيا مملكة قديمة على محيط اليونان العت...,History,https://en.wikipedia.org/wiki/Macedonia_(ancie...,88,56,NaN
105,The first government of ancient Macedonia was ...,أنشئت أول حكومة مقدونية على يد السلالة الأرغية...,History,https://en.wikipedia.org/wiki/Government_of_Ma...,139,144,NaN
67,Welding is a fabrication process that joins ma...,اللِحام هي عملية تصنيعية يتم فيها وصل مادتين ع...,Engineering and technology,https://en.wikipedia.org/wiki/Welding,211,195,NaN
57,The Hanford Site is a decommissioned nuclear p...,إن موقعَ هانفورد هو مخبر خارج عن الخدمة لتركيب...,Engineering and technology,https://en.wikipedia.org/wiki/Hanford_S,104,70,NaN
43,Mary Jane Richardson Jones (1819 – December 26...,كانت ماري جين ريتشاردسون جونز (1819 – 26 ديسمب...,Culture and society biographies,https://en.wikipedia.org/wiki/Mary_Jane_Richar...,147,97,NaN
31,Wife selling in England was a way of ending an...,عادة بيع الزوجة هي وسيلة بديلة للطلاق حيث كان ...,Culture and Society,https://en.wikipedia.org/wiki/Wife_selling_(En...,206,210,NaN
25,The name-letter effect is the tendency of peop...,تأثير حروف الاسم هي ظاهرة تُوَضِّح الاتجاه ال...,Culture and Society,https://en.wikipedia.org/wiki/Name-letter_effect,172,159,NaN
156,Gather Together in My Name (1974) is a memoir ...,اجتمعوا معًا على اسمي هي رواية صدرت عام 1974 ف...,Autobiographies and memoirs,\n\nhttps://en.wikipedia.org/wiki/Gather_Toge...,87,112,NaN
98,The Croatian Spring (Croatian: Hrvatsko prolje...,كان الربيع الكرواتي نزاعًا سياسيًا استمر منذ ...,History,https://en.wikipedia.org/wiki/Croatian_Spring,140,106,NaN
69,The cerebellum (pl.: cerebella or cerebellums...,المُخَيخ (اللاتينيّة: Cerebellum والتي تعني «ا...,Health and medicine,https://en.wikipedia.org/wiki/Cerebellum,144,118,NaN
128,The Nyon Conference was a diplomatic conferenc...,مؤتمر نيون هو مؤتمر دبلوماسي انعقد في نيون، سو...,History,https://en.wikipedia.org/wiki/Nyon_Conference,113,97,NaN
124,The Mormon handcart pioneers were participants...,رواد عربة اليد المورمونية هم الأفراد المشاركين...,History,https://en.wikipedia.org/wiki/Mormon_handcart_...,157,142,NaN
20,Freedom for the Thought That We Hate: A Biogra...,الحرية للفكر الذي نكره: نظرة على تاريخ التعدي...,Culture and Society,https://en.wikipedia.org/wiki/Freedom_for_the_...,226,201,NaN
46,"Mark Ivor Satin (born November 16, 1946) is an...",مارك إيفور ساتين (بالإنجليزية: Mark Satin)‏ (و...,Culture and society biographies,https://en.wikipedia.org/wiki/Mark_Satin,80,89,NaN
76,The 1740 Batavia massacre was a massacre and p...,مجزرة باتافيا هي مجزرة منظمة حدثت للإندونيسيي...,History,https://en.wikipedia.org/wiki/1740_Batavia_mas...,253,243,NaN
169,The Diary of a Nobody is an English comic nove...,مذكرات نكرة هي رواية إنجليزية هزلية كتبها الأخ...,"Novels, including graphic novels",https://en.wikipedia.org/wiki/The_Diary_of_a_N...,81,61,NaN
68,Amphetamine (contracted from alpha-methylphene...,الأمفيتامين مُنبِّه قوي للجهاز العصبي المركزي...,Health and medicine,https://en.wikipedia.org/wiki/Amphetamine,157,115,NaN
6,The Million Dollar Homepage is a website conce...,الصفحة الرئيسية المليون دولاریة هو موقع ابتكره...,Computing,https://en.wikipedia.org/wiki/The_Million_Doll...,131,117,NaN
133,The Saint-Sylvestre coup d'état was a coup d'é...,كان انقلاب سان سيلفستر انقلابا نظمه جان بيدل ب...,History,https://en.wikipedia.org/wiki/Saint-Sylvestre_...,134,124,NaN
170,Dr. No is the sixth novel by the English autho...,الطبيب. نو هي الرواية السادسة للمؤلف البريطاني...,"Novels, including graphic novels",https://en.wikipedia.org/wiki/Dr._No_(novel),49,41,NaN
164,Weird Tales is an American fantasy and horror ...,هي مجلة للأدب الرخيص أو البولب لصنف الفانتازيا...,Magazines and comics,https://en.wikipedia.org/wiki/Weird_Tales,104,87,NaN
79,"On November 11, 1960, a failed coup attempt ag...",في 11 نوفمبر 1960، كانت محاولة الانقلاب الفاش...,History,https://en.wikipedia.org/wiki/1960_South_Vietn...,145,113,NaN
113,Human habitation in the Sierra Nevada region o...,لأكثر من 3000 سنة عاشت جماعات سييرا ميوك، مونو...,History,https://en.wikipedia.org/wiki/History_of_the_Y...,144,112,NaN

In [ ]:
#train the whole test set
for index, row in tqdm(test_df.iterrows(), total = len(test_df), desc="Translating test set"):
  translation = gpt_translate(row['english_text'], row['Field'])
  test_df.at[index, 'gpt_translation'] = translation
  if translation is None:
        print(f"Failed translation for ID {index}")

Translating test set:   0%|          | 0/38 [00:00<?, ?it/s]/tmp/ipython-input-767924103.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'المؤرخ هي الرواية الأولى للكاتبة الأمريكية إليزابيث كوستوفا، ونُشرت عام 2005. تدمج حبكتها بين التاريخ والفولكلور المتعلق بفلاد المخوزق ونظيره الخيالي الكونت دراكولا. كان والد كوستوفا يروي لها قصصًا عن دراكولا عندما كانت طفلة، ولاحقًا ألهمتها تلك التجربة لتحويلها إلى رواية. عملت على الكتاب لمدة عشر سنوات ثم باعتها خلال بضعة أشهر لدار ليتل براون آند كومباني، التي اشترت حقوقها بمبلغ قدره مليونا دولار أمريكي.' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  test_df.at[index, 'gpt_translation'] = translation
Translating test set: 100%|██████████| 38/38 [14:44<00:00, 23.27s/it]

In [ ]:
output_path = '/content/drive/MyDrive/Colab Notebooks/test_df_translated(1).xlsx'
test_df.to_excel(output_path, index=True)

In [ ]:
test_df_translated = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/test_df_translated(1).xlsx")
test_df_translated

,id,english_text,arabic_reference,Field,Link,english_word_count,arabic_word_count,gpt_translation
0,176,The Historian is the 2005 debut novel of Ameri...,هي الرواية الأولى للكاتبة الأمريكية إليزابيث ك...,"Novels, including graphic novels",https://en.wikipedia.org/wiki/The_Historian,81,79,NaN
1,181,The Phantom Tollbooth is a children's fantasy ...,المحصل فانتوم هي رواية مغامرات خيالية للأطفال ...,"Novels, including graphic novels",https://en.wikipedia.org/wiki/The_Phantom_Toll...,107,95,NaN
2,112,"Solidarity, a Polish non-governmental trade un...",حركة تضامن هي نقابة عمالية غير حكومية أسسها لي...,History,https://en.wikipedia.org/wiki/History_of_Solid...,70,65,NaN
3,66,The Sholes and Glidden typewriter (also known ...,آلة شولز وغلايدن الكاتبة هي أول الآلات الكاتبة...,Engineering and technology,https://en.wikipedia.org/wiki/Sholes_and_Glidd...,115,90,NaN
4,102,"On 9 February 2001, about nine nautical miles ...",في 9 فبراير 2001 اصطدمت الغواصة يو إس إس غرينف...,History,https://en.wikipedia.org/wiki/Ehime_Maru_and_U...,99,82,NaN
5,16,The Cottingley Fairies appear in a series of f...,تظهر جنيات كوتينجلي في سلسلة من خمس صور التقط...,Culture and Society,https://en.wikipedia.org/wiki/Cottingley_Fairies,196,169,NaN
6,10,The Burke and Hare murders were a series of si...,ارتكب بورك وهير 16 جريمة قتل موزعة على فترات ا...,Culture and Society,https://en.wikipedia.org/wiki/Burke_and_Hare_m...,236,264,NaN
7,17,Mark Saunders was a British barrister who was ...,كان مارك سوندرز محاميًا بريطانيًا حين قُتل برص...,Culture and Society,https://en.wikipedia.org/wiki/Death_of_Mark_Sa...,180,182,NaN
8,142,The Coinage Act of 1873 or Mint Act of 1873 wa...,كان قانون سك العملة لعام 1873 أو قانون العملات...,Law,https://en.wikipedia.org/wiki/Coinage_Act_of_1...,100,82,NaN
9,125,"The murder of Julia Martha Thomas, dubbed the ...",إن مقتل جوليا مارثا توماس ، يطلق عليه اسم لغز ...,History,https://en.wikipedia.org/wiki/Murder_of_Julia_...,142,138,NaN
10,110,The history of Lithuania between 1219 and 1295...,يوثّق تاريخ ليتوانيا بين عامي 1219 و1295 تأسيس...,History,https://en.wikipedia.org/wiki/History_of_Lithu...,135,109,NaN
11,96,"The Palace of Westminster, the medieval royal ...",حريق البرلمان هو حريق اندلع في 16 أكتوبر 1834...,History,https://en.wikipedia.org/wiki/Burning_of_Parli...,90,72,NaN
12,19,Disco Demolition Night was a Major League Base...,كانت ليلة هدم ديسكو عبارة عن عرض ترويجي لدوري...,Culture and Society,https://en.wikipedia.org/wiki/Disco_Demolition...,105,86,NaN
13,165,Wonder Stories was an early American science f...,قصص العجائب هي مجلة خيال علمي أمريكية قديمة تم...,Magazines and comics,https://en.wikipedia.org/wiki/Wonder_Stories,70,66,NaN
14,86,"Alodia, also known as Alwa, was a medieval kin...",مملكة علوة، وتعرف أيضًا باسم ألوديا، هي مملكة ...,History,https://en.wikipedia.org/wiki/Alodia,171,160,NaN
15,121,"Macedonia, also called Macedon, was an ancient...",كانت مقدونيا مملكة قديمة على محيط اليونان العت...,History,https://en.wikipedia.org/wiki/Macedonia_(ancie...,88,56,NaN
16,105,The first government of ancient Macedonia was ...,أنشئت أول حكومة مقدونية على يد السلالة الأرغية...,History,https://en.wikipedia.org/wiki/Government_of_Ma...,139,144,NaN
17,67,Welding is a fabrication process that joins ma...,اللِحام هي عملية تصنيعية يتم فيها وصل مادتين ع...,Engineering and technology,https://en.wikipedia.org/wiki/Welding,211,195,NaN
18,57,The Hanford Site is a decommissioned nuclear p...,إن موقعَ هانفورد هو مخبر خارج عن الخدمة لتركيب...,Engineering and technology,https://en.wikipedia.org/wiki/Hanford_S,104,70,NaN
19,43,Mary Jane Richardson Jones (1819 – December 26...,كانت ماري جين ريتشاردسون جونز (1819 – 26 ديسمب...,Culture and society biographies,https://en.wikipedia.org/wiki/Mary_Jane_Richar...,147,97,NaN
20,31,Wife selling in England was a way of ending an...,عادة بيع الزوجة هي وسيلة بديلة للطلاق حيث كان ...,Culture and Society,https://en.wikipedia.org/wiki/Wife_selling_(En...,206,210,NaN
21,25,The name-letter effect is the tendency of peop...,تأثير حروف الاسم هي ظاهرة تُوَضِّح الاتجاه ال...,Culture and Society,https://en.wikipedia.org/wiki/Name-letter_effect,172,159,NaN
22,156,Gather Together in My Name (1974) is a memoir ...,اجتمعوا معًا على اسمي هي رواية صدرت عام 1974 ف...,Autobiographies and memoirs,\n\nhttps://en.wikipedia.org/wiki/Gather_Toge...,87,112,NaN
23,98,The Croatian Spring (Croatian: Hrvatsko prolje...,كان الربيع الكرواتي نزاعًا سياسيًا استمر منذ ...,History,https://en.wikipedia.org/wiki/Croatian_Spring,140,106,NaN
24,69,The cerebellum (pl.: cerebella or cerebellums...,المُخَيخ (اللاتينيّة: Cerebellum والتي تعني «ا...,Health and medicine,https://en.wikipedia.org/wiki/Cerebellum,144,118,NaN
25,128,The Nyon Conference was a diplomatic conferenc...,مؤتمر نيون هو مؤتمر دبلوماسي انعقد في نيون، سو...,History,https://en.wikipedia.org/wiki/Nyon_Conference,113,97,NaN
26,124,The Mormon handcart pioneers were participants...,رواد عربة اليد المورمونية هم الأفراد المشاركين...,History,https://en.wikipedia.org/wiki/Mormon_handcart_...,157,142,NaN
27,20,Freedom for the Thought That We Hate: A Biogra...,الحرية للفكر الذي نكره: نظرة على تاريخ التعدي...,Culture and Society,https://en.wikipedia.org/wiki/Freedom_for_the_...,226,201,NaN
28,46,"Mark Ivor Satin (born November 16, 1946) is an...",مارك إيفور ساتين (بالإنجليزية: Mark Satin)‏ (و...,Culture and society biographies,https://en.wikipedia.org/wiki/Mark_Satin,80,89,NaN
29,76,The 1740 Batavia massacre was a massacre and p...,مجزرة باتافيا هي مجزرة منظمة حدثت للإندونيسيي...,History,https://en.wikipedia.org/wiki/1740_Batavia_mas...,253,243,NaN
30,169,The Diary of a Nobody is an English comic nove...,مذكرات نكرة هي رواية إنجليزية هزلية كتبها الأخ...,"Novels, including graphic novels",https://en.wikipedia.org/wiki/The_Diary_of_a_N...,81,61,NaN
31,68,Amphetamine (contracted from alpha-methylphene...,الأمفيتامين مُنبِّه قوي للجهاز العصبي المركزي...,Health and medicine,https://en.wikipedia.org/wiki/Amphetamine,157,115,NaN
32,6,The Million Dollar Homepage is a website conce...,الصفحة الرئيسية المليون دولاریة هو موقع ابتكره...,Computing,https://en.wikipedia.org/wiki/The_Million_Doll...,131,117,NaN
33,133,The Saint-Sylvestre coup d'état was a coup d'é...,كان انقلاب سان سيلفستر انقلابا نظمه جان بيدل ب...,History,https://en.wikipedia.org/wiki/Saint-Sylvestre_...,134,124,NaN
34,170,Dr. No is the sixth novel by the English autho...,الطبيب. نو هي الرواية السادسة للمؤلف البريطاني...,"Novels, including graphic novels",https://en.wikipedia.org/wiki/Dr._No_(novel),49,41,NaN
35,164,Weird Tales is an American fantasy and horror ...,هي مجلة للأدب الرخيص أو البولب لصنف الفانتازيا...,Magazines and comics,https://en.wikipedia.org/wiki/Weird_Tales,104,87,NaN
36,79,"On November 11, 1960, a failed coup attempt ag...",في 11 نوفمبر 1960، كانت محاولة الانقلاب الفاش...,History,https://en.wikipedia.org/wiki/1960_South_Vietn...,145,113,NaN
37,113,Human habitation in the Sierra Nevada region o...,لأكثر من 3000 سنة عاشت جماعات سييرا ميوك، مونو...,History,https://en.wikipedia.org/wiki/History_of_the_Y...,144,112,NaN

In [ ]:
translations_test = test_df_translated['gpt_translation'].tolist()
references_test = test_df_translated['arabic_reference'].tolist()

In [ ]:
# Compute overall BLEU
bleu = BLEU()
# Filter out non-string translations
translations_test_filtered = [t for t in translations_test if isinstance(t, str)]
references_test_filtered = [references_test[i] for i, t in enumerate(translations_test) if isinstance(t, str)]
bleu_score = bleu.corpus_score(translations_test_filtered, [references_test_filtered]).score
print(f"Overall BLEU score for subset: {bleu_score:.2f}")

Overall BLEU score for subset: 17.73

In [ ]:
data_test = [
    {"src": row['english_text'], "mt": row['gpt_translation'], "ref": row['arabic_reference']}
    for _, row in test_df_translated.iterrows()
]

In [ ]:
comet_scores_test = model.predict(data_test, batch_size=8, gpus=0)

INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: False, used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 5/5 [05:11<00:00, 62.27s/it]

In [ ]:
print(f"Overall COMET score for test set: {comet_scores_test.system_score:.4f}")

Overall COMET score for test set: 0.8649

# **AI Agent**

In [ ]:
openAI_Key = userdata.get('NMT_GPT5mini')

In [ ]:
client = OpenAI(api_key=openAI_Key)

we drop the arabic reference from the test set to keep the agent self contained

In [ ]:
test_df_agent = test_df.drop(columns=['Link','english_word_count','arabic_word_count'])
test_df_agent

,english_text,arabic_reference,Field
id,,,
176,The Historian is the 2005 debut novel of Ameri...,هي الرواية الأولى للكاتبة الأمريكية إليزابيث ك...,"Novels, including graphic novels"
181,The Phantom Tollbooth is a children's fantasy ...,المحصل فانتوم هي رواية مغامرات خيالية للأطفال ...,"Novels, including graphic novels"
112,"Solidarity, a Polish non-governmental trade un...",حركة تضامن هي نقابة عمالية غير حكومية أسسها لي...,History
66,The Sholes and Glidden typewriter (also known ...,آلة شولز وغلايدن الكاتبة هي أول الآلات الكاتبة...,Engineering and technology
102,"On 9 February 2001, about nine nautical miles ...",في 9 فبراير 2001 اصطدمت الغواصة يو إس إس غرينف...,History
16,The Cottingley Fairies appear in a series of f...,تظهر جنيات كوتينجلي في سلسلة من خمس صور التقط...,Culture and Society
10,The Burke and Hare murders were a series of si...,ارتكب بورك وهير 16 جريمة قتل موزعة على فترات ا...,Culture and Society
17,Mark Saunders was a British barrister who was ...,كان مارك سوندرز محاميًا بريطانيًا حين قُتل برص...,Culture and Society
142,The Coinage Act of 1873 or Mint Act of 1873 wa...,كان قانون سك العملة لعام 1873 أو قانون العملات...,Law
125,"The murder of Julia Martha Thomas, dubbed the ...",إن مقتل جوليا مارثا توماس ، يطلق عليه اسم لغز ...,History
110,The history of Lithuania between 1219 and 1295...,يوثّق تاريخ ليتوانيا بين عامي 1219 و1295 تأسيس...,History
96,"The Palace of Westminster, the medieval royal ...",حريق البرلمان هو حريق اندلع في 16 أكتوبر 1834...,History
19,Disco Demolition Night was a Major League Base...,كانت ليلة هدم ديسكو عبارة عن عرض ترويجي لدوري...,Culture and Society
165,Wonder Stories was an early American science f...,قصص العجائب هي مجلة خيال علمي أمريكية قديمة تم...,Magazines and comics
86,"Alodia, also known as Alwa, was a medieval kin...",مملكة علوة، وتعرف أيضًا باسم ألوديا، هي مملكة ...,History
121,"Macedonia, also called Macedon, was an ancient...",كانت مقدونيا مملكة قديمة على محيط اليونان العت...,History
105,The first government of ancient Macedonia was ...,أنشئت أول حكومة مقدونية على يد السلالة الأرغية...,History
67,Welding is a fabrication process that joins ma...,اللِحام هي عملية تصنيعية يتم فيها وصل مادتين ع...,Engineering and technology
57,The Hanford Site is a decommissioned nuclear p...,إن موقعَ هانفورد هو مخبر خارج عن الخدمة لتركيب...,Engineering and technology
43,Mary Jane Richardson Jones (1819 – December 26...,كانت ماري جين ريتشاردسون جونز (1819 – 26 ديسمب...,Culture and society biographies
31,Wife selling in England was a way of ending an...,عادة بيع الزوجة هي وسيلة بديلة للطلاق حيث كان ...,Culture and Society
25,The name-letter effect is the tendency of peop...,تأثير حروف الاسم هي ظاهرة تُوَضِّح الاتجاه ال...,Culture and Society
156,Gather Together in My Name (1974) is a memoir ...,اجتمعوا معًا على اسمي هي رواية صدرت عام 1974 ف...,Autobiographies and memoirs
98,The Croatian Spring (Croatian: Hrvatsko prolje...,كان الربيع الكرواتي نزاعًا سياسيًا استمر منذ ...,History
69,The cerebellum (pl.: cerebella or cerebellums...,المُخَيخ (اللاتينيّة: Cerebellum والتي تعني «ا...,Health and medicine
128,The Nyon Conference was a diplomatic conferenc...,مؤتمر نيون هو مؤتمر دبلوماسي انعقد في نيون، سو...,History
124,The Mormon handcart pioneers were participants...,رواد عربة اليد المورمونية هم الأفراد المشاركين...,History
20,Freedom for the Thought That We Hate: A Biogra...,الحرية للفكر الذي نكره: نظرة على تاريخ التعدي...,Culture and Society
46,"Mark Ivor Satin (born November 16, 1946) is an...",مارك إيفور ساتين (بالإنجليزية: Mark Satin)‏ (و...,Culture and society biographies
76,The 1740 Batavia massacre was a massacre and p...,مجزرة باتافيا هي مجزرة منظمة حدثت للإندونيسيي...,History
169,The Diary of a Nobody is an English comic nove...,مذكرات نكرة هي رواية إنجليزية هزلية كتبها الأخ...,"Novels, including graphic novels"
68,Amphetamine (contracted from alpha-methylphene...,الأمفيتامين مُنبِّه قوي للجهاز العصبي المركزي...,Health and medicine
6,The Million Dollar Homepage is a website conce...,الصفحة الرئيسية المليون دولاریة هو موقع ابتكره...,Computing
133,The Saint-Sylvestre coup d'état was a coup d'é...,كان انقلاب سان سيلفستر انقلابا نظمه جان بيدل ب...,History
170,Dr. No is the sixth novel by the English autho...,الطبيب. نو هي الرواية السادسة للمؤلف البريطاني...,"Novels, including graphic novels"
164,Weird Tales is an American fantasy and horror ...,هي مجلة للأدب الرخيص أو البولب لصنف الفانتازيا...,Magazines and comics
79,"On November 11, 1960, a failed coup attempt ag...",في 11 نوفمبر 1960، كانت محاولة الانقلاب الفاش...,History
113,Human habitation in the Sierra Nevada region o...,لأكثر من 3000 سنة عاشت جماعات سييرا ميوك، مونو...,History

In [ ]:
path = '/content/drive/MyDrive/Colab Notebooks/test_df_agent.xlsx'
test_df_agent.to_excel(path, index=True)

In [ ]:
test_df_agent = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/test_df_agent.xlsx")
test_df_agent

,id,english_text,arabic_reference,Field
0,176,The Historian is the 2005 debut novel of Ameri...,هي الرواية الأولى للكاتبة الأمريكية إليزابيث ك...,"Novels, including graphic novels"
1,181,The Phantom Tollbooth is a children's fantasy ...,المحصل فانتوم هي رواية مغامرات خيالية للأطفال ...,"Novels, including graphic novels"
2,112,"Solidarity, a Polish non-governmental trade un...",حركة تضامن هي نقابة عمالية غير حكومية أسسها لي...,History
3,66,The Sholes and Glidden typewriter (also known ...,آلة شولز وغلايدن الكاتبة هي أول الآلات الكاتبة...,Engineering and technology
4,102,"On 9 February 2001, about nine nautical miles ...",في 9 فبراير 2001 اصطدمت الغواصة يو إس إس غرينف...,History
5,16,The Cottingley Fairies appear in a series of f...,تظهر جنيات كوتينجلي في سلسلة من خمس صور التقط...,Culture and Society
6,10,The Burke and Hare murders were a series of si...,ارتكب بورك وهير 16 جريمة قتل موزعة على فترات ا...,Culture and Society
7,17,Mark Saunders was a British barrister who was ...,كان مارك سوندرز محاميًا بريطانيًا حين قُتل برص...,Culture and Society
8,142,The Coinage Act of 1873 or Mint Act of 1873 wa...,كان قانون سك العملة لعام 1873 أو قانون العملات...,Law
9,125,"The murder of Julia Martha Thomas, dubbed the ...",إن مقتل جوليا مارثا توماس ، يطلق عليه اسم لغز ...,History
10,110,The history of Lithuania between 1219 and 1295...,يوثّق تاريخ ليتوانيا بين عامي 1219 و1295 تأسيس...,History
11,96,"The Palace of Westminster, the medieval royal ...",حريق البرلمان هو حريق اندلع في 16 أكتوبر 1834...,History
12,19,Disco Demolition Night was a Major League Base...,كانت ليلة هدم ديسكو عبارة عن عرض ترويجي لدوري...,Culture and Society
13,165,Wonder Stories was an early American science f...,قصص العجائب هي مجلة خيال علمي أمريكية قديمة تم...,Magazines and comics
14,86,"Alodia, also known as Alwa, was a medieval kin...",مملكة علوة، وتعرف أيضًا باسم ألوديا، هي مملكة ...,History
15,121,"Macedonia, also called Macedon, was an ancient...",كانت مقدونيا مملكة قديمة على محيط اليونان العت...,History
16,105,The first government of ancient Macedonia was ...,أنشئت أول حكومة مقدونية على يد السلالة الأرغية...,History
17,67,Welding is a fabrication process that joins ma...,اللِحام هي عملية تصنيعية يتم فيها وصل مادتين ع...,Engineering and technology
18,57,The Hanford Site is a decommissioned nuclear p...,إن موقعَ هانفورد هو مخبر خارج عن الخدمة لتركيب...,Engineering and technology
19,43,Mary Jane Richardson Jones (1819 – December 26...,كانت ماري جين ريتشاردسون جونز (1819 – 26 ديسمب...,Culture and society biographies
20,31,Wife selling in England was a way of ending an...,عادة بيع الزوجة هي وسيلة بديلة للطلاق حيث كان ...,Culture and Society
21,25,The name-letter effect is the tendency of peop...,تأثير حروف الاسم هي ظاهرة تُوَضِّح الاتجاه ال...,Culture and Society
22,156,Gather Together in My Name (1974) is a memoir ...,اجتمعوا معًا على اسمي هي رواية صدرت عام 1974 ف...,Autobiographies and memoirs
23,98,The Croatian Spring (Croatian: Hrvatsko prolje...,كان الربيع الكرواتي نزاعًا سياسيًا استمر منذ ...,History
24,69,The cerebellum (pl.: cerebella or cerebellums...,المُخَيخ (اللاتينيّة: Cerebellum والتي تعني «ا...,Health and medicine
25,128,The Nyon Conference was a diplomatic conferenc...,مؤتمر نيون هو مؤتمر دبلوماسي انعقد في نيون، سو...,History
26,124,The Mormon handcart pioneers were participants...,رواد عربة اليد المورمونية هم الأفراد المشاركين...,History
27,20,Freedom for the Thought That We Hate: A Biogra...,الحرية للفكر الذي نكره: نظرة على تاريخ التعدي...,Culture and Society
28,46,"Mark Ivor Satin (born November 16, 1946) is an...",مارك إيفور ساتين (بالإنجليزية: Mark Satin)‏ (و...,Culture and society biographies
29,76,The 1740 Batavia massacre was a massacre and p...,مجزرة باتافيا هي مجزرة منظمة حدثت للإندونيسيي...,History
30,169,The Diary of a Nobody is an English comic nove...,مذكرات نكرة هي رواية إنجليزية هزلية كتبها الأخ...,"Novels, including graphic novels"
31,68,Amphetamine (contracted from alpha-methylphene...,الأمفيتامين مُنبِّه قوي للجهاز العصبي المركزي...,Health and medicine
32,6,The Million Dollar Homepage is a website conce...,الصفحة الرئيسية المليون دولاریة هو موقع ابتكره...,Computing
33,133,The Saint-Sylvestre coup d'état was a coup d'é...,كان انقلاب سان سيلفستر انقلابا نظمه جان بيدل ب...,History
34,170,Dr. No is the sixth novel by the English autho...,الطبيب. نو هي الرواية السادسة للمؤلف البريطاني...,"Novels, including graphic novels"
35,164,Weird Tales is an American fantasy and horror ...,هي مجلة للأدب الرخيص أو البولب لصنف الفانتازيا...,Magazines and comics
36,79,"On November 11, 1960, a failed coup attempt ag...",في 11 نوفمبر 1960، كانت محاولة الانقلاب الفاش...,History
37,113,Human habitation in the Sierra Nevada region o...,لأكثر من 3000 سنة عاشت جماعات سييرا ميوك، مونو...,History

In [ ]:
with open('/content/drive/MyDrive/Colab Notebooks/Translator_Prompt.txt') as file:
  translator_prompt = file.read()
translator_prompt

"You are an expert translator specializing in English to Modern Standard Arabic translations. Your goal is to produce high-quality, accurate translations that are culturally appropriate, stylistically natural, and aligned with professional standards as per ISO 17100.\nPurpose: Produce translations of encyclopedic Wikipedia excerpts for evaluation in a machine translation research.\nTarget Audience: Arabic-speaking general readers.\nStyle: Encyclopedic.\nLanguage Pair: English to Modern Standard Arabic.\nDomain Context: The text is from a Wikipedia article in the field of {field}.\nHere are five high-quality example translations to guide your output:\nExample 1 (Field: History):\nEnglish: The Palace of Versailles is a royal château in Versailles, Yvelines, in the Île-de-France region of France. When the château was built, Versailles was a country village; today, however, it is a suburb of Paris, some 20 kilometres southwest of the French capital. The court of Versailles was the centre of political power in France from 1682, when Louis XIV moved from Paris, until the royal family was forced to return to the capital in October 1789 after the beginning of the French Revolution. Versailles is therefore famous not only as a building, but as well as a symbol of the system of absolute monarchy of the Ancien Régime.\nArabic: قصر فرساي هو قلعة ملكية تقع في فرساي في منطقة إيل دو فرانس الفرنسية. عندما بُنيت القلعة، كانت فرساي مجرد قرية؛ ولكن اليوم تُعتبر فرساي من ضواحي باريس وتبعد حوالي عشرين كيلومترًا عن العاصمة الفرنسية. كان بلاط فرساي مركزًا للسلطة السياسية في فرنسا من عام 1682، عندما قرر لويس الرابع عشر الانتقال من باريس، حتى أجبِرت العائلة الملكية على العودة إلى العاصمة في أكتوبر 1789 بعد بداية الثورة الفرنسية. لا تُعد فرساي مجرد مبنى شهير بل رمزًا لنظام الملكية المطلقة للنظام القديم\nExample 2 (Field: Law):\nEnglish: The Coinage Act of 1965, Pub. L. 89–81, 79 Stat. 254, enacted July 23, 1965, eliminated silver from the circulating United States dime (ten-cent piece) and quarter dollar coins. It also reduced the silver content of the half dollar from 90 percent to 40 percent; silver in the half dollar was subsequently eliminated by a 1970 law.\nArabic: قانون العملة لعام 1965، 254، صدر في 23 يوليو/تموز 1965، وألغى الفضة من العُملات المعدنية فئة العشرة سنتات و الربع دولار المتداولة في الولايات المتحدة. كما أدى ذلك إلى خفض محتوى الفضة في نصف الدولار من 90 في المائة إلى 40 في المائة؛ وألغى بعد ذلك الفضة في نصف الدولار بموجب قانون صدر عام 1970\nExample 3 (Field: Magazines and comics):\nEnglish: Alice in the Country of Hearts is a Japanese female-oriented visual novel developed by Quin Rose. The game is a re-imagining of Lewis Carroll's classic 1865 novel Alice's Adventures in Wonderland. There are multiple sequel games, as well as multiple manga series, licensed in North America originally by Tokyopop and later by Yen Press and Seven Seas Entertainment. An original video animation adaptation was announced for release in November 2008, but was later delayed. Instead, an anime film adaptation produced by Asahi Production was released in Japanese theaters in July 2011.\nArabic: أليس في بلاد القلوب هي رواية مرئية يابانية مغامرة رومانسية موجهة للإناث، طورت من قِبل كوين روز. اللعبة هي إعادة تخيل لرواية لويس كارول الكلاسيكية: مغامرات أليس في بلاد العجائب. كانت هناك عدة تتمات للعبة، فضلا عن العديد من سلاسل مانغا. فيديو رسوم متحركة أصلي أعلن عن موعد إصداره في نوفمبر 2008، ولكن تم تأجيل الإطلاق في وقت لاحق. فيلم أنمي من إنتاج اساهي برودكشن صدر في المسارح اليابانية في يوليو 2011\nExample 4 (Field: Novels)\nEnglish: A debut novel is the first novel a novelist publishes. Debut novels are often the author's first opportunity to make an impact on the publishing industry, and thus the success or failure of a debut novel can affect the ability of the author to publish in the future. Sometimes new novelists will self-publish their debut novels, because publishing houses will not risk the capital needed to market books by an unknown author to the public.\nArabic: الرواية الأولى هي أول عمل روائي منشور للكاتب، وغالبًا ما تُشكّل الفرصة الأولى له لإثبات حضوره في عالم النشر. يمكن لنجاح أو فشل هذه الرواية أن يؤثر بشكل مباشر على قدرة الكاتب على الاستمرار في النشر مستقبلاً. في كثير من الحالات، يلجأ الروائيون الجدد إلى نشر رواياتهم الأولى بأنفسهم، نظرًا لتردد دور النشر في المخاطرة بالاستثمار في أعمال لكتاب غير معروفي\nExample 5 (Field: Education)\nEnglish: The Education Program for Gifted Youth (EPGY) at Stanford University was a loose collection of gifted education programs formerly located within Stanford Pre-Collegiate Studies program.[1] EPGY included distance and residential summer courses for students of all ages. Many of the courses were distance learning, meaning that courses were taught remotely via the Internet, rather than in the traditional classroom setting. Courses targeted students from elementary school up to advanced college graduate. Subjects offered included: Mathematics, English, Humanities, Physics, and Computer Science. Stanford Pre-Collegiate Studies is similar to the Center for Talented Youth at the Johns Hopkins University in terms of certain objectives.\nArabic: برنامج التعليم للشباب الموهوبين (EPGY) في جامعة ستانفورد، هو مجموعة فضفاضة من برامج التعليم للموهوبين التي كانت موجودة سابقا في دراسات ستانفورد قبل الجامعية في جامعة ستانفورد. وشملت برامج إبغي دورات المسافة والصيف السكنية للطلاب من جميع الأعمار. وكان العديد من الدورات التعلم عن بعد، وهذا يعني أن الدورات تدرس عن بعد عن طريق الإنترنت، وليس في إعدادالفصول الدراسية التقليدية. دورات استهدفت الطلاب من المدرسة الابتدائية حتى خريج الكلية المتقدمة. الموضوعات المقدمة شملت: الرياضيات، واللغة الإنجليزية، والعلوم الإنسانية، والفيزياء، وعلوم الكمبيوتر. تشبه دراسات ستانفورد ما قبل الجامعية مركز الشباب الموهوبين في جامعة جونز هوبكنز من حيث الأهداف المعينة\nOutput only the Arabic translation without any additional explanations or text.\n"

In [ ]:
with open('/content/drive/MyDrive/Colab Notebooks/Evaluator_Prompt.txt') as file:
  evaluator_prompt = file.read()
evaluator_prompt

'You are an expert translator specializing in English to Modern Standard Arabic translations. Your task is to evaluate LLM-generated translations of encyclopedic Wikipedia excerpts for evaluation in a machine translation research. You must assess these translations on:\n1. Adequacy: How well does the translation convey the meaning of the English source text? (5=perfect, 1=unacceptable)\n2. Fluency: How natural and grammatically correct is the Arabic translation for a native Arabic speaker? (5=perfect, 1=unacceptable)\n3. Style: How well does the translation maintain the encyclopedic/Wikipedia style and tone of the source? (5=perfect, 1=unacceptable)\nProvide:\nA score from 1 to 5 for each metric.\n2-3 specific improvements (e.g., "Replace term X with Y for accuracy").\nInput: English Text: {english_text} Translation: {translation} Field: {field}\nOutput format: \nAdequacy: [score]/5 \nFluency: [score]/5 \nStyle: [score]/5 \nImprovements:\n[Improvement 1]\n[Improvement 2, if applicable]\n[Improvement 3, if applicable]\nOutput only the score for each metric and the improvements without any additional explanations or text.'

In [ ]:
with open('/content/drive/MyDrive/Colab Notebooks/Refiner_Prompt.txt') as file:
  refiner_prompt = file.read()
refiner_prompt

'You are an expert translator specializing in English to Modern Standard Arabic translations. Your task is to refine the provided Arabic translation based on the improvements below, ensuring high adequacy, fluency, and encyclopedic style suitable for Arabic Wikipedia. Focus only on the suggested improvements without additional text.\nInput: Original Translation: {translation} Critique: {critique} Field: {field}\nOutput only the refined Arabic translation.'

In [ ]:
# Translate
def translate(text_id, text_english, text_field):
    translator_prompt_with_field = translator_prompt.format(field=text_field)
    try:
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": translator_prompt_with_field},
                {"role": "user", "content": text_english}
            ],
            temperature=0.3,
            max_tokens=1000
        )
        arabic_translation = response.choices[0].message.content.strip()
        if not arabic_translation:
            print(f"Empty translation for text ID: {text_id}")
            return None
        return arabic_translation
    except Exception as e:
        print(f"Translation error for text ID: {text_id}: {e}")
        return None

In [ ]:
# Evaluate
def evaluate(text_id, text_english, text_field, arabic_translation):
    if arabic_translation is None:
        return None, {'Adequacy': None, 'Fluency': None, 'Style': None}
    scores = {'Adequacy': None, 'Fluency': None, 'Style': None}
    prompt = evaluator_prompt.format(english_text=text_english, translation=arabic_translation, field=text_field)
    try:
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": prompt},
                {"role": "user", "content": "Evaluate the translation."}
            ],
            temperature=0.3,
            max_tokens=500
        )
        eval_text = response.choices[0].message.content.strip()

        # Parse evaluation output
        score_pattern = r"(Adequacy|Fluency|Style): (\d)/5"
        improvement_pattern = r"Improvements:\n([\s\S]*)"
        scores_match = re.findall(score_pattern, eval_text)
        improvements_match = re.search(improvement_pattern, eval_text)

        for metric, score in scores_match:
            scores[metric] = int(score)
        improvements = improvements_match.group(1).strip().split('\n') if improvements_match else []
        return eval_text, scores
    except Exception as e:
        print(f"Evaluation error for text ID: {text_id}: {e}")
        return None, scores

In [ ]:
# Refine
def refine(text_id, arabic_translation, eval_text, text_field):
    if arabic_translation is None or eval_text is None:
        return arabic_translation
    prompt = refiner_prompt.format(translation=arabic_translation, critique=eval_text, field=text_field)
    try:
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": prompt},
                {"role": "user", "content": "Refine the translation."}
            ],
            temperature=0.3,
            max_tokens=1000
        )
        refined_translation = response.choices[0].message.content.strip()
        if not refined_translation:
            print(f"Empty refinement for text ID: {text_id}")
            return arabic_translation
        return refined_translation
    except Exception as e:
        print(f"Refinement error for text ID: {text_id}: {e}")
        return arabic_translation

In [ ]:
# Translate -> Evaluate (with scores) -> Refine translation if needed
def translate_evaluate_assess(text_id, text_english, text_field):
    arabic_translation = translate(text_id, text_english, text_field)
    if arabic_translation is None:
        return None, {'Adequacy': None, 'Fluency': None, 'Style': None}
    eval_text, scores = evaluate(text_id, text_english, text_field, arabic_translation)
    refined_translation = refine(text_id, arabic_translation, eval_text, text_field)
    return refined_translation, scores #scores from the evaluation step

In [ ]:
test_df = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/test_df_agent.xlsx")
test_df['agent_translation'] = None
test_df['adequacy_score'] = None
test_df['fluency_score'] = None
test_df['style_score'] = None

In [ ]:
test_df

,id,english_text,arabic_reference,Field,agent_translation,adequacy_score,fluency_score,style_score
0,176,The Historian is the 2005 debut novel of Ameri...,هي الرواية الأولى للكاتبة الأمريكية إليزابيث ك...,"Novels, including graphic novels",None,None,None,None
1,181,The Phantom Tollbooth is a children's fantasy ...,المحصل فانتوم هي رواية مغامرات خيالية للأطفال ...,"Novels, including graphic novels",None,None,None,None
2,112,"Solidarity, a Polish non-governmental trade un...",حركة تضامن هي نقابة عمالية غير حكومية أسسها لي...,History,None,None,None,None
3,66,The Sholes and Glidden typewriter (also known ...,آلة شولز وغلايدن الكاتبة هي أول الآلات الكاتبة...,Engineering and technology,None,None,None,None
4,102,"On 9 February 2001, about nine nautical miles ...",في 9 فبراير 2001 اصطدمت الغواصة يو إس إس غرينف...,History,None,None,None,None
5,16,The Cottingley Fairies appear in a series of f...,تظهر جنيات كوتينجلي في سلسلة من خمس صور التقط...,Culture and Society,None,None,None,None
6,10,The Burke and Hare murders were a series of si...,ارتكب بورك وهير 16 جريمة قتل موزعة على فترات ا...,Culture and Society,None,None,None,None
7,17,Mark Saunders was a British barrister who was ...,كان مارك سوندرز محاميًا بريطانيًا حين قُتل برص...,Culture and Society,None,None,None,None
8,142,The Coinage Act of 1873 or Mint Act of 1873 wa...,كان قانون سك العملة لعام 1873 أو قانون العملات...,Law,None,None,None,None
9,125,"The murder of Julia Martha Thomas, dubbed the ...",إن مقتل جوليا مارثا توماس ، يطلق عليه اسم لغز ...,History,None,None,None,None
10,110,The history of Lithuania between 1219 and 1295...,يوثّق تاريخ ليتوانيا بين عامي 1219 و1295 تأسيس...,History,None,None,None,None
11,96,"The Palace of Westminster, the medieval royal ...",حريق البرلمان هو حريق اندلع في 16 أكتوبر 1834...,History,None,None,None,None
12,19,Disco Demolition Night was a Major League Base...,كانت ليلة هدم ديسكو عبارة عن عرض ترويجي لدوري...,Culture and Society,None,None,None,None
13,165,Wonder Stories was an early American science f...,قصص العجائب هي مجلة خيال علمي أمريكية قديمة تم...,Magazines and comics,None,None,None,None
14,86,"Alodia, also known as Alwa, was a medieval kin...",مملكة علوة، وتعرف أيضًا باسم ألوديا، هي مملكة ...,History,None,None,None,None
15,121,"Macedonia, also called Macedon, was an ancient...",كانت مقدونيا مملكة قديمة على محيط اليونان العت...,History,None,None,None,None
16,105,The first government of ancient Macedonia was ...,أنشئت أول حكومة مقدونية على يد السلالة الأرغية...,History,None,None,None,None
17,67,Welding is a fabrication process that joins ma...,اللِحام هي عملية تصنيعية يتم فيها وصل مادتين ع...,Engineering and technology,None,None,None,None
18,57,The Hanford Site is a decommissioned nuclear p...,إن موقعَ هانفورد هو مخبر خارج عن الخدمة لتركيب...,Engineering and technology,None,None,None,None
19,43,Mary Jane Richardson Jones (1819 – December 26...,كانت ماري جين ريتشاردسون جونز (1819 – 26 ديسمب...,Culture and society biographies,None,None,None,None
20,31,Wife selling in England was a way of ending an...,عادة بيع الزوجة هي وسيلة بديلة للطلاق حيث كان ...,Culture and Society,None,None,None,None
21,25,The name-letter effect is the tendency of peop...,تأثير حروف الاسم هي ظاهرة تُوَضِّح الاتجاه ال...,Culture and Society,None,None,None,None
22,156,Gather Together in My Name (1974) is a memoir ...,اجتمعوا معًا على اسمي هي رواية صدرت عام 1974 ف...,Autobiographies and memoirs,None,None,None,None
23,98,The Croatian Spring (Croatian: Hrvatsko prolje...,كان الربيع الكرواتي نزاعًا سياسيًا استمر منذ ...,History,None,None,None,None
24,69,The cerebellum (pl.: cerebella or cerebellums...,المُخَيخ (اللاتينيّة: Cerebellum والتي تعني «ا...,Health and medicine,None,None,None,None
25,128,The Nyon Conference was a diplomatic conferenc...,مؤتمر نيون هو مؤتمر دبلوماسي انعقد في نيون، سو...,History,None,None,None,None
26,124,The Mormon handcart pioneers were participants...,رواد عربة اليد المورمونية هم الأفراد المشاركين...,History,None,None,None,None
27,20,Freedom for the Thought That We Hate: A Biogra...,الحرية للفكر الذي نكره: نظرة على تاريخ التعدي...,Culture and Society,None,None,None,None
28,46,"Mark Ivor Satin (born November 16, 1946) is an...",مارك إيفور ساتين (بالإنجليزية: Mark Satin)‏ (و...,Culture and society biographies,None,None,None,None
29,76,The 1740 Batavia massacre was a massacre and p...,مجزرة باتافيا هي مجزرة منظمة حدثت للإندونيسيي...,History,None,None,None,None
30,169,The Diary of a Nobody is an English comic nove...,مذكرات نكرة هي رواية إنجليزية هزلية كتبها الأخ...,"Novels, including graphic novels",None,None,None,None
31,68,Amphetamine (contracted from alpha-methylphene...,الأمفيتامين مُنبِّه قوي للجهاز العصبي المركزي...,Health and medicine,None,None,None,None
32,6,The Million Dollar Homepage is a website conce...,الصفحة الرئيسية المليون دولاریة هو موقع ابتكره...,Computing,None,None,None,None
33,133,The Saint-Sylvestre coup d'état was a coup d'é...,كان انقلاب سان سيلفستر انقلابا نظمه جان بيدل ب...,History,None,None,None,None
34,170,Dr. No is the sixth novel by the English autho...,الطبيب. نو هي الرواية السادسة للمؤلف البريطاني...,"Novels, including graphic novels",None,None,None,None
35,164,Weird Tales is an American fantasy and horror ...,هي مجلة للأدب الرخيص أو البولب لصنف الفانتازيا...,Magazines and comics,None,None,None,None
36,79,"On November 11, 1960, a failed coup attempt ag...",في 11 نوفمبر 1960، كانت محاولة الانقلاب الفاش...,History,None,None,None,None
37,113,Human habitation in the Sierra Nevada region o...,لأكثر من 3000 سنة عاشت جماعات سييرا ميوك، مونو...,History,None,None,None,None

In [ ]:
for idx, row in tqdm(test_df.iterrows(), total=len(test_df), desc="Processing test set"):
    refined_translation, scores = translate_evaluate_assess(idx, row['english_text'], row['Field'])
    test_df.at[idx, 'agent_translation'] = refined_translation
    if scores:
        test_df.at[idx, 'adequacy_score'] = scores['Adequacy']
        test_df.at[idx, 'fluency_score'] = scores['Fluency']
        test_df.at[idx, 'style_score'] = scores['Style']
    if refined_translation is None:
        print(f"Failed translation for ID: {idx}")
    time.sleep(1)

Processing test set: 100%|██████████| 38/38 [06:34<00:00, 10.38s/it]

In [ ]:
output_path = '/content/drive/MyDrive/Colab Notebooks/test_df_agent_translated.csv'
test_df.to_csv(output_path, index=True)

In [ ]:
test_df_translated = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/test_df_agent_translated.csv')
test_df_translated

,Unnamed: 0,id,english_text,arabic_reference,Field,agent_translation,adequacy_score,fluency_score,style_score
0,0,176,The Historian is the 2005 debut novel of Ameri...,هي الرواية الأولى للكاتبة الأمريكية إليزابيث ك...,"Novels, including graphic novels",المؤرخ هي الرواية الأولى للكاتبة الأمريكية إلي...,5,5,5
1,1,181,The Phantom Tollbooth is a children's fantasy ...,المحصل فانتوم هي رواية مغامرات خيالية للأطفال ...,"Novels, including graphic novels",بوابة الأشباح هي رواية مغامرات خيالية للأطفال ...,4,4,4
2,2,112,"Solidarity, a Polish non-governmental trade un...",حركة تضامن هي نقابة عمالية غير حكومية أسسها لي...,History,"تأسست ""التضامن""، وهي نقابة عمالية غير حكومية ب...",5,5,5
3,3,66,The Sholes and Glidden typewriter (also known ...,آلة شولز وغلايدن الكاتبة هي أول الآلات الكاتبة...,Engineering and technology,كانت آلة الكتابة من نوع شولز وغليدن (المعروفة ...,5,5,5
4,4,102,"On 9 February 2001, about nine nautical miles ...",في 9 فبراير 2001 اصطدمت الغواصة يو إس إس غرينف...,History,في 9 فبراير 2001، وعلى بعد حوالي تسعة أميال بح...,5,5,5
5,5,16,The Cottingley Fairies appear in a series of f...,تظهر جنيات كوتينجلي في سلسلة من خمس صور التقط...,Culture and Society,تظهر جنيات كوتينغلي في سلسلة من خمس صور فوتوغر...,4,4,4
6,6,10,The Burke and Hare murders were a series of si...,ارتكب بورك وهير 16 جريمة قتل موزعة على فترات ا...,Culture and Society,كانت جرائم بيرك وهير سلسلة من ستة عشر جريمة قت...,5,5,5
7,7,17,Mark Saunders was a British barrister who was ...,كان مارك سوندرز محاميًا بريطانيًا حين قُتل برص...,Culture and Society,مارك سوندرز كان محاميًا بريطانيًا تم إطلاق الن...,5,5,5
8,8,142,The Coinage Act of 1873 or Mint Act of 1873 wa...,كان قانون سك العملة لعام 1873 أو قانون العملات...,Law,قانون العملة لعام 1873 أو قانون سك العملات لعا...,5,5,5
9,9,125,"The murder of Julia Martha Thomas, dubbed the ...",إن مقتل جوليا مارثا توماس ، يطلق عليه اسم لغز ...,History,كانت جريمة قتل جوليا مارثا توماس، التي أطلق عل...,5,5,5
10,10,110,The history of Lithuania between 1219 and 1295...,يوثّق تاريخ ليتوانيا بين عامي 1219 و1295 تأسيس...,History,تاريخ ليتوانيا بين عامي 1219 و1295 يتعلق بتأسي...,4,4,4
11,11,96,"The Palace of Westminster, the medieval royal ...",حريق البرلمان هو حريق اندلع في 16 أكتوبر 1834...,History,قصر ويستمنستر، القصر الملكي الوسيط الذي يُستخد...,5,5,5
12,12,19,Disco Demolition Night was a Major League Base...,كانت ليلة هدم ديسكو عبارة عن عرض ترويجي لدوري...,Culture and Society,كانت ليلة تدمير الديسكو حدثًا ترويجيًا في دوري...,5,5,5
13,13,165,Wonder Stories was an early American science f...,قصص العجائب هي مجلة خيال علمي أمريكية قديمة تم...,Magazines and comics,"كانت مجلة ""قصص العجائب"" واحدة من أوائل المجلات...",5,5,5
14,14,86,"Alodia, also known as Alwa, was a medieval kin...",مملكة علوة، وتعرف أيضًا باسم ألوديا، هي مملكة ...,History,الألوديا، المعروفة أيضًا باسم ألوى، كانت مملكة...,5,5,5
15,15,121,"Macedonia, also called Macedon, was an ancient...",كانت مقدونيا مملكة قديمة على محيط اليونان العت...,History,مقدونيا، المعروفة أيضًا بمقدون، كانت مملكة قدي...,5,5,5
16,16,105,The first government of ancient Macedonia was ...,أنشئت أول حكومة مقدونية على يد السلالة الأرغية...,History,تأسست أول حكومة في مقدونيا القديمة على يد سلال...,5,5,5
17,17,67,Welding is a fabrication process that joins ma...,اللِحام هي عملية تصنيعية يتم فيها وصل مادتين ع...,Engineering and technology,اللحام هو عملية تصنيع تربط المواد، عادة المعاد...,5,5,5
18,18,57,The Hanford Site is a decommissioned nuclear p...,إن موقعَ هانفورد هو مخبر خارج عن الخدمة لتركيب...,Engineering and technology,موقع هانفورد هو مجمع لإنتاج الطاقة النووية تم ...,4,4,4
19,19,43,Mary Jane Richardson Jones (1819 – December 26...,كانت ماري جين ريتشاردسون جونز (1819 – 26 ديسمب...,Culture and society biographies,ماري جين ريتشاردسون جونز (1819 – 26 ديسمبر 190...,5,5,5
20,20,31,Wife selling in England was a way of ending an...,عادة بيع الزوجة هي وسيلة بديلة للطلاق حيث كان ...,Culture and Society,بيع الزوجات في إنجلترا كان وسيلة لإنهاء زواج غ...,5,5,5
21,21,25,The name-letter effect is the tendency of peop...,تأثير حروف الاسم هي ظاهرة تُوَضِّح الاتجاه ال...,Culture and Society,تأثير حرف الاسم هو ميل الأشخاص لتفضيل الحروف ا...,5,5,5
22,22,156,Gather Together in My Name (1974) is a memoir ...,اجتمعوا معًا على اسمي هي رواية صدرت عام 1974 ف...,Autobiographies and memoirs,اجتمعوا معًا باسمي (1974) هو مذكرات للكاتبة وا...,5,5,5
23,23,98,The Croatian Spring (Croatian: Hrvatsko prolje...,كان الربيع الكرواتي نزاعًا سياسيًا استمر منذ ...,History,ربيع كرواتيا (بالكرواتية: Hrvatsko proljeće)، ...,5,5,5
24,24,69,The cerebellum (pl.: cerebella or cerebellums...,المُخَيخ (اللاتينيّة: Cerebellum والتي تعني «ا...,Health and medicine,"المخيخ (جمع: مخاخ أو مخاخات؛ اللاتينية تعني ""ا...",5,5,5
25,25,128,The Nyon Conference was a diplomatic conferenc...,مؤتمر نيون هو مؤتمر دبلوماسي انعقد في نيون، سو...,History,كانت مؤتمر نيون مؤتمرًا دبلوماسيًا عُقد في نيو...,5,5,5
26,26,124,The Mormon handcart pioneers were participants...,رواد عربة اليد المورمونية هم الأفراد المشاركين...,History,كان رواد العربات اليدوية المورمونية مشاركين في...,4,4,4
27,27,20,Freedom for the Thought That We Hate: A Biogra...,الحرية للفكر الذي نكره: نظرة على تاريخ التعدي...,Culture and Society,حرية الفكر الذي نكرهه: سيرة ذاتية للتعديل الأو...,5,5,5
28,28,46,"Mark Ivor Satin (born November 16, 1946) is an...",مارك إيفور ساتين (بالإنجليزية: Mark Satin)‏ (و...,Culture and society biographies,مارك إيفور ساتين (ولد في 16 نوفمبر 1946) هو عا...,5,5,5
29,29,76,The 1740 Batavia massacre was a massacre and p...,مجزرة باتافيا هي مجزرة منظمة حدثت للإندونيسيي...,History,مجزرة باتافيا عام 1740 كانت مجزرة ومذابح قام ب...,5,5,5
30,30,169,The Diary of a Nobody is an English comic nove...,مذكرات نكرة هي رواية إنجليزية هزلية كتبها الأخ...,"Novels, including graphic novels",يوميات شخص عادي هي رواية كوميدية إنجليزية كتبه...,5,5,5
31,31,68,Amphetamine (contracted from alpha-methylphene...,الأمفيتامين مُنبِّه قوي للجهاز العصبي المركزي...,Health and medicine,الأمفيتامين (المختصر من ألفا ميثيل فينيل إيثيل...,5,5,5
32,32,6,The Million Dollar Homepage is a website conce...,الصفحة الرئيسية المليون دولاریة هو موقع ابتكره...,Computing,صفحة المليون دولار هي موقع ويب تم إنشاؤه في عا...,4,4,4
33,33,133,The Saint-Sylvestre coup d'état was a coup d'é...,كان انقلاب سان سيلفستر انقلابا نظمه جان بيدل ب...,History,انقلاب سانت-سيلفستر هو انقلاب نفذه جان-بديل بو...,5,5,5
34,34,170,Dr. No is the sixth novel by the English autho...,الطبيب. نو هي الرواية السادسة للمؤلف البريطاني...,"Novels, including graphic novels",دكتور نو هي الرواية السادسة للكاتب الإنجليزي إ...,5,5,5
35,35,164,Weird Tales is an American fantasy and horror ...,هي مجلة للأدب الرخيص أو البولب لصنف الفانتازيا...,Magazines and comics,وييرد تيلز هي مجلة أمريكية خيالية ورعب تأسست ع...,5,5,5
36,36,79,"On November 11, 1960, a failed coup attempt ag...",في 11 نوفمبر 1960، كانت محاولة الانقلاب الفاش...,History,في 11 نوفمبر 1960، قاد العقيد فوانغ فانه دونغ ...,4,4,4
37,37,113,Human habitation in the Sierra Nevada region o...,لأكثر من 3000 سنة عاشت جماعات سييرا ميوك، مونو...,History,يعود تاريخ السكن البشري في منطقة سييرا نيفادا ...,5,5,5

In [ ]:
test_df_translated

,Unnamed: 0,id,english_text,arabic_reference,Field,agent_translation,adequacy_score,fluency_score,style_score
0,0,176,The Historian is the 2005 debut novel of Ameri...,هي الرواية الأولى للكاتبة الأمريكية إليزابيث ك...,"Novels, including graphic novels",المؤرخ هي الرواية الأولى للكاتبة الأمريكية إلي...,5,5,5
1,1,181,The Phantom Tollbooth is a children's fantasy ...,المحصل فانتوم هي رواية مغامرات خيالية للأطفال ...,"Novels, including graphic novels",بوابة الأشباح هي رواية مغامرات خيالية للأطفال ...,4,4,4
2,2,112,"Solidarity, a Polish non-governmental trade un...",حركة تضامن هي نقابة عمالية غير حكومية أسسها لي...,History,"تأسست ""التضامن""، وهي نقابة عمالية غير حكومية ب...",5,5,5
3,3,66,The Sholes and Glidden typewriter (also known ...,آلة شولز وغلايدن الكاتبة هي أول الآلات الكاتبة...,Engineering and technology,كانت آلة الكتابة من نوع شولز وغليدن (المعروفة ...,5,5,5
4,4,102,"On 9 February 2001, about nine nautical miles ...",في 9 فبراير 2001 اصطدمت الغواصة يو إس إس غرينف...,History,في 9 فبراير 2001، وعلى بعد حوالي تسعة أميال بح...,5,5,5
5,5,16,The Cottingley Fairies appear in a series of f...,تظهر جنيات كوتينجلي في سلسلة من خمس صور التقط...,Culture and Society,تظهر جنيات كوتينغلي في سلسلة من خمس صور فوتوغر...,4,4,4
6,6,10,The Burke and Hare murders were a series of si...,ارتكب بورك وهير 16 جريمة قتل موزعة على فترات ا...,Culture and Society,كانت جرائم بيرك وهير سلسلة من ستة عشر جريمة قت...,5,5,5
7,7,17,Mark Saunders was a British barrister who was ...,كان مارك سوندرز محاميًا بريطانيًا حين قُتل برص...,Culture and Society,مارك سوندرز كان محاميًا بريطانيًا تم إطلاق الن...,5,5,5
8,8,142,The Coinage Act of 1873 or Mint Act of 1873 wa...,كان قانون سك العملة لعام 1873 أو قانون العملات...,Law,قانون العملة لعام 1873 أو قانون سك العملات لعا...,5,5,5
9,9,125,"The murder of Julia Martha Thomas, dubbed the ...",إن مقتل جوليا مارثا توماس ، يطلق عليه اسم لغز ...,History,كانت جريمة قتل جوليا مارثا توماس، التي أطلق عل...,5,5,5
10,10,110,The history of Lithuania between 1219 and 1295...,يوثّق تاريخ ليتوانيا بين عامي 1219 و1295 تأسيس...,History,تاريخ ليتوانيا بين عامي 1219 و1295 يتعلق بتأسي...,4,4,4
11,11,96,"The Palace of Westminster, the medieval royal ...",حريق البرلمان هو حريق اندلع في 16 أكتوبر 1834...,History,قصر ويستمنستر، القصر الملكي الوسيط الذي يُستخد...,5,5,5
12,12,19,Disco Demolition Night was a Major League Base...,كانت ليلة هدم ديسكو عبارة عن عرض ترويجي لدوري...,Culture and Society,كانت ليلة تدمير الديسكو حدثًا ترويجيًا في دوري...,5,5,5
13,13,165,Wonder Stories was an early American science f...,قصص العجائب هي مجلة خيال علمي أمريكية قديمة تم...,Magazines and comics,"كانت مجلة ""قصص العجائب"" واحدة من أوائل المجلات...",5,5,5
14,14,86,"Alodia, also known as Alwa, was a medieval kin...",مملكة علوة، وتعرف أيضًا باسم ألوديا، هي مملكة ...,History,الألوديا، المعروفة أيضًا باسم ألوى، كانت مملكة...,5,5,5
15,15,121,"Macedonia, also called Macedon, was an ancient...",كانت مقدونيا مملكة قديمة على محيط اليونان العت...,History,مقدونيا، المعروفة أيضًا بمقدون، كانت مملكة قدي...,5,5,5
16,16,105,The first government of ancient Macedonia was ...,أنشئت أول حكومة مقدونية على يد السلالة الأرغية...,History,تأسست أول حكومة في مقدونيا القديمة على يد سلال...,5,5,5
17,17,67,Welding is a fabrication process that joins ma...,اللِحام هي عملية تصنيعية يتم فيها وصل مادتين ع...,Engineering and technology,اللحام هو عملية تصنيع تربط المواد، عادة المعاد...,5,5,5
18,18,57,The Hanford Site is a decommissioned nuclear p...,إن موقعَ هانفورد هو مخبر خارج عن الخدمة لتركيب...,Engineering and technology,موقع هانفورد هو مجمع لإنتاج الطاقة النووية تم ...,4,4,4
19,19,43,Mary Jane Richardson Jones (1819 – December 26...,كانت ماري جين ريتشاردسون جونز (1819 – 26 ديسمب...,Culture and society biographies,ماري جين ريتشاردسون جونز (1819 – 26 ديسمبر 190...,5,5,5
20,20,31,Wife selling in England was a way of ending an...,عادة بيع الزوجة هي وسيلة بديلة للطلاق حيث كان ...,Culture and Society,بيع الزوجات في إنجلترا كان وسيلة لإنهاء زواج غ...,5,5,5
21,21,25,The name-letter effect is the tendency of peop...,تأثير حروف الاسم هي ظاهرة تُوَضِّح الاتجاه ال...,Culture and Society,تأثير حرف الاسم هو ميل الأشخاص لتفضيل الحروف ا...,5,5,5
22,22,156,Gather Together in My Name (1974) is a memoir ...,اجتمعوا معًا على اسمي هي رواية صدرت عام 1974 ف...,Autobiographies and memoirs,اجتمعوا معًا باسمي (1974) هو مذكرات للكاتبة وا...,5,5,5
23,23,98,The Croatian Spring (Croatian: Hrvatsko prolje...,كان الربيع الكرواتي نزاعًا سياسيًا استمر منذ ...,History,ربيع كرواتيا (بالكرواتية: Hrvatsko proljeće)، ...,5,5,5
24,24,69,The cerebellum (pl.: cerebella or cerebellums...,المُخَيخ (اللاتينيّة: Cerebellum والتي تعني «ا...,Health and medicine,"المخيخ (جمع: مخاخ أو مخاخات؛ اللاتينية تعني ""ا...",5,5,5
25,25,128,The Nyon Conference was a diplomatic conferenc...,مؤتمر نيون هو مؤتمر دبلوماسي انعقد في نيون، سو...,History,كانت مؤتمر نيون مؤتمرًا دبلوماسيًا عُقد في نيو...,5,5,5
26,26,124,The Mormon handcart pioneers were participants...,رواد عربة اليد المورمونية هم الأفراد المشاركين...,History,كان رواد العربات اليدوية المورمونية مشاركين في...,4,4,4
27,27,20,Freedom for the Thought That We Hate: A Biogra...,الحرية للفكر الذي نكره: نظرة على تاريخ التعدي...,Culture and Society,حرية الفكر الذي نكرهه: سيرة ذاتية للتعديل الأو...,5,5,5
28,28,46,"Mark Ivor Satin (born November 16, 1946) is an...",مارك إيفور ساتين (بالإنجليزية: Mark Satin)‏ (و...,Culture and society biographies,مارك إيفور ساتين (ولد في 16 نوفمبر 1946) هو عا...,5,5,5
29,29,76,The 1740 Batavia massacre was a massacre and p...,مجزرة باتافيا هي مجزرة منظمة حدثت للإندونيسيي...,History,مجزرة باتافيا عام 1740 كانت مجزرة ومذابح قام ب...,5,5,5
30,30,169,The Diary of a Nobody is an English comic nove...,مذكرات نكرة هي رواية إنجليزية هزلية كتبها الأخ...,"Novels, including graphic novels",يوميات شخص عادي هي رواية كوميدية إنجليزية كتبه...,5,5,5
31,31,68,Amphetamine (contracted from alpha-methylphene...,الأمفيتامين مُنبِّه قوي للجهاز العصبي المركزي...,Health and medicine,الأمفيتامين (المختصر من ألفا ميثيل فينيل إيثيل...,5,5,5
32,32,6,The Million Dollar Homepage is a website conce...,الصفحة الرئيسية المليون دولاریة هو موقع ابتكره...,Computing,صفحة المليون دولار هي موقع ويب تم إنشاؤه في عا...,4,4,4
33,33,133,The Saint-Sylvestre coup d'état was a coup d'é...,كان انقلاب سان سيلفستر انقلابا نظمه جان بيدل ب...,History,انقلاب سانت-سيلفستر هو انقلاب نفذه جان-بديل بو...,5,5,5
34,34,170,Dr. No is the sixth novel by the English autho...,الطبيب. نو هي الرواية السادسة للمؤلف البريطاني...,"Novels, including graphic novels",دكتور نو هي الرواية السادسة للكاتب الإنجليزي إ...,5,5,5
35,35,164,Weird Tales is an American fantasy and horror ...,هي مجلة للأدب الرخيص أو البولب لصنف الفانتازيا...,Magazines and comics,وييرد تيلز هي مجلة أمريكية خيالية ورعب تأسست ع...,5,5,5
36,36,79,"On November 11, 1960, a failed coup attempt ag...",في 11 نوفمبر 1960، كانت محاولة الانقلاب الفاش...,History,في 11 نوفمبر 1960، قاد العقيد فوانغ فانه دونغ ...,4,4,4
37,37,113,Human habitation in the Sierra Nevada region o...,لأكثر من 3000 سنة عاشت جماعات سييرا ميوك، مونو...,History,يعود تاريخ السكن البشري في منطقة سييرا نيفادا ...,5,5,5

Firs, let us compute the overall adequacy, fluency, and style scores of the test data and compare them to human annotated scores

In [ ]:
average_adequacy = test_df_translated['adequacy_score'].mean()
average_fluency = test_df_translated['fluency_score'].mean()
average_style = test_df_translated['style_score'].mean()
print(f"Average adequacy score: {average_adequacy}")
print(f"Average fluency score: {average_fluency}")
print(f"Average style score: {average_style}")

Average adequacy score: 4.815789473684211
Average fluency score: 4.815789473684211
Average style score: 4.815789473684211

In [ ]:
translations = test_df_translated['agent_translation'].tolist()
references = test_df_translated['arabic_reference'].tolist()
references

['هي الرواية الأولى للكاتبة الأمريكية إليزابيث كوستوفا، نشرت في عام 2005. المؤرخ تمزج الرواية بين التاريخ الحقيقي وبين الفولكلور الشعبي عن فلاد شيبي، وهو المعروف في الحكايات الخيالية باسم الكونت دراكولا. استلهمت كوستوفا هذه الرواية من القصص التي كان أبوها يرويها لها في طفولتها عن دراكولا، وحين كبرت قررت أن تكتب رواية عن تلك القصص. وعملت على تأليف الكتاب لمدة عشر سنوات، ثم باعته بعد بضعة أشهر لدار النشر الأمريكية «ليتل وبراون وشركاه»، في مقابل 2 مليون دولار أمريكي ',
 'المحصل فانتوم هي رواية مغامرات خيالية للأطفال كتبها نورتون جاستر ، مع رسوم توضيحية لجولز فايفر ، نُشرت لأول مرة في عام 1961. تتبع القصة صبيًا صغيرًا يشعر بالملل يُدعى ميلو يتلقى بشكل غير متوقع كشكًا سحريًا للجباية ينقله إلى مملكة الحكمة التي كانت مزدهرة، ولكنها الآن مضطربة. جنبا إلى جنب مع كلب اسمه توك ومعهم الهراء، يذهب ميلو في مهمة بحثية عن القلعة في الهواء بحثًا عن أميرات المملكة المنفيتين، وهما قافية و منطق. بينما يتعلم ميلو دروسًا قيمة، يجد حب التعلم في قصة مليئة بالتورية والتلاعب بالألفاظ، مثل استكشاف المعاني الحرفية للتعابير الاصطلاحية. ',
 'حركة تضامن هي نقابة عمالية غير حكومية أسسها ليخ فاونسا وآخرون، في 14 آب/أغسطس 1980، في مدينة لينين شيبارد (غدانسك شيبارد الآن). وأصبحت أول نقابة عمالية في الكتلة الشرقية. وتميزت بانتشارها واسع النطاق، وعدم ميلها إلى العنف، حيث ادعى البعض أن عدد أعضائها وصل إلى 9,4 مليون عضو. كما عملت على مكافحة الشيوعية، التي كانت في أوجها حين ذاك، ويُنسَب إليها الفضل أيضًا في سقوطها. ',
 'آلة شولز وغلايدن الكاتبة هي أول الآلات الكاتبة الناجحة تجارياً. صٌمِّمت أساساً من قبل المخترع الأمريكي كروستوفر شولز، تم تطويرها بمساعدة زميله سامويل جورج سول وكارلوس غليدن. بدأ العمل في 1867، ولكن سول غادر الفريق بعد فترة وجيزة تاركاً مكانه لجيمس دينسمور الذي دعمهم مادياً وكان القوة الدافعة خلف تطور الآلة المستمر. بعد عدة محاولات لتصنيع الآلة، تم الاستحواذ عليها من قبل E. Remington and Sons في بدايات 1873. رامينغتون الذي كان مصنع سلاح يتطلع لأن يوسع نطاق إنتاجه، حسَّن الآلة قبل أن يعرضها في السوق يوم 1 يوليو 1874. \n\n ',
 'في 9 فبراير 2001 اصطدمت الغواصة يو إس إس غرينفيل (غواصة أمريكية من فئة لوس أنجلوس) بسفينة إهيمه مارو ، سفينة تدريب خاضعة لمدرسة ثانوية سَمَكية بمحافظة إهيمه اليابانية) على بعد نحو 9 أميال بحرية (17 كم) جنوب جزيرة أواهو بولاية هاواي. كانت الغواصة تستعرض لبعض زوارها المدنيين المميزين مناورة الطوارئ المدعوة «الطفو بنفخ الصابورة». وبينما هي تطفو، صدمت إهيمه مارو، فغرقت السفينة بعد 10 دقائق. كان على متن السفينة 35 إنسانًا، مات منهم تسعة: 4 طلابِ ثانوية، ومدرسان، و3 من طاقمها. ',
 ' تظهر جنيات كوتينجلي في سلسلة من خمس صور التقطتها إيلي رايت (1901-1988م) وفرانسيس غريفيث (1907-1986م)، وهما ابنا عم صغيران عاشا في كوتينجلي، بالقرب من برادفورد في إنجلترا. في عام 1917م، عندما تم التقاط أول صورتين، كانت إلسي تبلغ من العمر 16 عامًا وفرانسيس في التاسعة من عمرها. لفتت الصور انتباه الكاتب السير آرثر كونان دويل، الذي استخدمها لتوضيح مقال عن الجنيات كان قد كلف بكتابته في طبعة عيد الميلاد عام 1920 من مجلة ستراند . كان دويل، باعتباره روحانيًا، متحمسًا للصور، وفسرها على أنها دليل واضح ومرئي على الظواهر النفسية. كان رد الفعل العام مختلطًا. قبل البعض الصور على أنها أصلية، بينما اعتقد البعض الآخر أنها مزيفة. \nانخفض الاهتمام بجنيات كوتينجلي تدريجيًا بعد عام 1921م. تزوجت الفتاتان وعاشتا في الخارج لفترة من الوقت بعد أن كبرت، ومع ذلك استمرت الصور في جذب انتباه الجمهور. في عام 1966م، تعقب مراسل من صحيفة ديلي إكسبريس إلسي، التي كانت قد عادت إلى المملكة المتحدة. تركت إلسي الباب مفتوحاً أمام احتمال أنها اعتقدت أنها صورت أفكارها، وأصبحت وسائل الإعلام مهتمة مرة أخرى بالقصة. ',
 'ارتكب بورك وهير 16 جريمة قتل موزعة على فترات امتدت إلى عشرة أشهر في عام 1828 في مدينة أدنبرة في أسكتلندا. وكان ويليام بورك وويليام هير بعد ارتكابهم لهذه الجرائم يبيعون الجثث على الدكتور روبرت نوكس ليقوم بتشريحها وعرضها على طلابه في محاضراته. \nكانت مدينة إدنبرة مركزاً أوروبياً رائداً في مجال علم دراسة التشريح في أوائل القرن التاسع عشر، وفي وقت من الأوقات واجه المركز عجزا في تأمين الأعداد الكافية من الجثث بطرق نظامية وذلك بسبب الطلب المتنامي عليها. وينص القانون الإسكتلندي على أن تأمين الجثث لأغراض طبية لا يكون إلا عن طريق من لقوا حتفهم في السجن أو عن طريق حالات الانتحار، أو من اللقطاء والأيتام. وأدى هذا النقص الشديد في الحصول على الجثث إلى زيادة في سرقة جثث الأموات من القبور على يد مجموعة أُطلق عليها لاحقا اسم «رجال البعث». وفاقمت الاجراءات المتخذة الرامية إلى ضمان عدم سرقة الأموات من قبورهم مشكلة هذا النقص. وعندما توفي أحد المُستأجرين في نُزل الرجل هير، سارع هير إلى صديقه بورك طالباً منه المشورة، فقرر الاثنين بيع جثة الرجل على الدكتور نوكس. وحصل الاثنان على 7 جنيهات في مقابل الجثة، وكان المبلغ بالنسبة لهم مبلغا سخيا. \nوبعد هذه الحادثة بشهرين تقريبا، كانت هناك امرأة تسكن في نُزل هير وكانت السيدة تعاني من الحُمى في وقتها، فخشي هير على زبائنه من النفور من نزله وتركه بسبب مرض السيدة، فعمد الاثنان، هير وبورك، على قتلها وبيع جثمانها للدكتور نوكس. واستمر الرجلان على هذه الحالة بالقتل وربما أن زوجتي هير وبورك كانتا على علم بجرائم زوجيهما. في النهاية انفضح أمر الرجلين وذلك بعد ما اكتشف أحد النُزلاء جثة السيدة مارغريت دوكرتي وهي آخر ضحاياهم، فهرول مُسرعا وأبلغ الشرطة بالجريمة. ',
 'كان مارك سوندرز محاميًا بريطانيًا حين قُتل برصاص الشرطة في السادس من مايو / أيار 2008 في حصار دام خمس ساعاتٍ حول منزله الذي يقع في ساحة ماركهام في تشيلسي بلندن . حيث عَمل سوندرز كمحامي طلاقٍ ناجح وكان يعاني من إدمان الكحول والاكتئاب. فقدكان يتصرف بغرابة في الساعات التي سبقت الحادثة حيث كان يشرب الكحول بإفراط. قُبيل الساعة 17:00 بوقت قصير (بتوقيت جرينتش ، التوقيت العالمي المنسق +1 )، أبلَغ الجيران الشرطة أن ساندرز يطلق النار ببندقيته من خلال نافذته. فعندما وصل رجال الشرطة وهم مسلحون، أطلق ساندرز النار على سياراتهم وبدأ الحصار. وانضم عدد كبير من رجال الشرطة في الحصار حيث اتخذوا مواقعهم في المباني والشوارع المحيطة. كان أطلاق النار بين ساندرز والشرطة متبادلًا على جولتين متتاليتين، و أصابت الشرطة ساندرز بجروح طفيفة. بعد حوالي 20 دقيقة من الجولة السابقة من إطلاق النار، حول الساعة 21:30، لوح ساندرز بالبندقية من النافذة. وبينما أخفض سلاحه باتجاه مجموعة من رجال الشرطة، أطلق سبعة من رجال الشرطة 11 طلقة، منها خمسة على الأقل أصابته. دخلت الشرطة بعدها بدقائق إلى شقته ونقلوا ساندرز إلى سيارة إسعاف التي كانت في الانتظار، حيث أعلن عن وفاته. ',
 'كان قانون سك العملة لعام 1873 أو قانون العملات الرابع، هو بمثابة مراجعة عامة للقوانين المتعلقة بسك العملة في الولايات المتحدة. من خلال إنهاء حق حاملي السبائك الفضية في تحويلها إلى دولارات فضية قياسية، مع السماح لحاملي الذهب بالاستمرار في تحويل سبائكهم إلى نقود، أنشأ القانون معيارًا ذهبيًا بشكل افتراضي. كما سمحت بدولار تجاري، بمناقصة قانونية محدودة، مخصص للتصدير، بشكل رئيسي إلى آسيا، وألغت ثلاث عملات معدنية صغيرة. أدى هذا الفعل إلى نتائج مثيرة للجدل وندد به النقاد باعتباره «جريمة عام 73». ',
 'إن مقتل جوليا مارثا توماس ، يطلق عليه اسم لغز بارنز أو جريمة ريتشموند من قبل الصحافة، كانت واحدة من أعتى الجرائم في وقت متأخر من القرن 19 في بريطانيا. توماس، وهي أرملة في الخمسينات من عمرها عاشت في ريتشموند في جنوب غرب لندن، اغتيلت في 2 مارس 1879 من قبل خادمتها، كيت ويبستر، وهي أيرلندية البالغة من العمر 30 عاما ولها تاريخ من السرقة. تخلصت ويبستر من الجسم عن طريق تمزيقه، وقامت بغلي اللحم قبالة العظام، ورمت معظم ما تبقى في نهر التايمز. وزعم أنه، على الرغم من أن ذلك لم يثبت أبدا، أنها عرضت الدهون إلى الجيران وأطفال الشوارع ك دهون وشحم. تم انتشال جزء من بقايا توماس في وقت لاحق من النهر. بقي رأسها مقطوعا وفي عداد المفقودين حتى أكتوبر 2010، عندما تم العثور على الجمجمة أثناء أعمال البناء التي يجري تنفيذها للسير ديفيد أتينبورو. ',
 'يوثّق تاريخ ليتوانيا بين عامي 1219 و1295 تأسيس دولة ليتوانيا الأولى وتاريخها المبكر، أي دوقية ليتوانيا الكبرى. تمثل بداية القرن الثالث عشر نهاية عصور ما قبل التاريخ في ليتوانيا. سُجّل التاريخ الليتواني ابتداءً من هذه النقطة في السجلات والمعاهدات ووثائق مكتوبة أخرى. في عام 1219، وقّع 21 دوقًا ليتوانيًا معاهدة سلام مع غاليسيا فولينا. حظي هذا الحدث بقبول واسع باعتباره أول دليل على أن قبائل البلطيق كانت متحدةً ومتماسكة. على الرغم من الحرب المستمرة مع تنظيمين مسيحيين هما التنظيم الليفوني والفرسان التويتونيون، تأسست دوقية ليتوانيا الكبرى واكتسبت بعض السيطرة على أراضي بلاك روثينيا، وبولاتسك، ومينسك، ومناطق أخرى شرق ليتوانيا الحالية التي أصبحت ضعيفة وغير حصينة بعد سقوط كيفان روس. \n\n ',
 ' حريق البرلمان هو حريق اندلع في 16 أكتوبر 1834 ودمر قصر وستمنستر، وهو قصر من القرون الوسطى وكان يعد مقر برلمان المملكة المتحدة. نتج الحريق جراء اشتعال بعض الألواح الخشبية التي كانت تستخدم حتى عام 1826 في تدوين إجراءات المحاسبة التابعة للخزانة العامة. تم التخلص من بعض الألواح الخشبية في الأفران الموجودة تحت مبنى مجلس اللوردات مما أدى إلى ملء المداخن الموجودة تحت طابق غرفات اللوردات بالسخام حتى وصل إلى حوائط المبنى. ',
 ' كانت ليلة هدم ديسكو عبارة عن عرض ترويجي لدوري البيسبول الرئيسي (MLB) يوم الخميس ، 12 يوليو 1979 ، في كوميسكي بارك في شيكاغو ، إلينوي ، والتي انتهت بأعمال شغب. في ذروة الحدث ، تم تفجير صندوق مليء بسجلات الديسكو في الملعب بين مباريات ثنائية الرأس المزدوجة بين شيكاغو وايت سوكس وديترويت تايجرز . جاء الكثير من الحاضرين لمشاهدة الانفجار بدلاً من الألعاب واندفعوا إلى الميدان بعد التفجير. لقد تضرر الملعب بسبب الانفجار والمشجعين لدرجة أن أبيض Sox طُلب منه التنازل عن المباراة الثانية للنمور. ',
 'قصص العجائب هي مجلة خيال علمي أمريكية قديمة تم إصدارها تحت العديد من المُسميات من عام 1929 إلي 1955. أنشائها هوغو جيرنزباك عام 1929 بعد أن فقد سيطرته على مجلته الأولي للخيال العلمي، وهي قصص مذهلة، عندما تعرضت شركته الإعلامية المجرب للنشر للإفلاس. وخلال شهور قليلة من الإفلاس، أصدر جيرنسباك ثلاث مجلات جديدة: قصص عجائب الجو، وقصص عجائب العلوم، وعجائب العلوم الفصلية (تصدر كل 3 شهور). \n\n ',
 'مملكة علوة، وتعرف أيضًا باسم ألوديا، هي مملكة نوبية قامت في العصور الوسطى على ما هو الآن جنوب ووسط السودان. كانت عاصمتها مدينة سوبا، وتقع بالقرب من الخرطوم الحديثة عند التقاء النيلين الأزرق والأبيض. \nتأسست علوة في وقت ما بعد سقوط مملكة كوش القديمة، نحو 350 بعد الميلاد، وقد ورد ذكرها لأول مرة في السجلات التاريخية في عام 569. كانت آخر الممالك النوبية الثلاث التي دخلت المسيحية في عام 580، بعد نوباتيا والمقرة. من المحتمل أن تكون قد وصلت إلى ذروتها خلال القرنين التاسع والثاني عشر عندما أظهرت السجلات أنها تفوقت على جارتها الشمالية، المقرة، من حيث الحجم والقوة العسكرية والازدهار الاقتصادي، ولكنها حافظت معها على روابط سلالات وثيقة. ونظرًا إلى كونها دولة كبيرة ومتعددة الثقافات، كانت مملكة علوة تُدار من قبل ملك قوي وحكام مقاطعات يعينهم. وُصِفت العاصمة سوبا بأنها مدينة ذات «مساكن واسعة وكنائس مليئة بالذهب والحدائق»، وازدهرت كمركز تجاري. ووصلتها البضائع من المقرة والشرق الأوسط وغرب إفريقيا والهند وحتى الصين. ازدهرت معرفة القراءة والكتابة باللغتين النوبية واليونانية. ',
 'كانت مقدونيا مملكة قديمة على محيط اليونان العتيقة والكلاسيكية، ولاحقًا الدولة المهيمنة في اليونان الهلنستية. تأسست المملكة وحكمتها في البداية السلالة الأرغية الملكية، تبعتها السلالات الأنتيبترية والأنتيغونية. كان موطن المقدونيين القدماء في أقرب مملكة تتمركز في الجزء الشمالي الشرقي من شبه الجزيرة اليونانية، ويحدها إبيروس من الغرب، وبايون من الشمال، وتراقيا من الشرق، وثسلي من الجنوب. ',
 'أنشئت أول حكومة مقدونية على يد السلالة الأرغية في وقت ما خلال فترة المملكة القديمة (بين القرنين الثامن والخامس قبل الميلاد). لا يُعرف سوى معلومات قليلة جدًا عن أصل المؤسسات الحكومية المقدونية قبل عهد الملك فيليب الثاني (حكم من 359 ق.م - 336 ق.م) بسبب نقص السجلات التاريخية التي توثق لهذه للمرحلة الأخيرة من عهد اليونان الكلاسيكية (480 ق.م - 336 ق.م). استمرت هذه المؤسسات في التطور تحت حكم خليفة فيليب الإسكندر الأكبر والسلالات التالية التي حكمت في عهد اليونان الهلنستية (336 ق.م - 146 ق.م). بعد الانتصار الروماني في الحرب المقدونية الثالثة وفرض الإقامة الجبرية على بيرسيوس المقدوني في عام 168 قبل الميلاد، ألغيت المملكة المقدونية واستبدلت بأربع جمهوريات مشتقة منها. لكن النظام الملكي قام مرة ثانية في مقدونيا لفترة وجيزة على يد أندريسكوس (150 ق.م - 148 ق.م)، لكن حكمه انهار بعد انتصار الرومان في الحرب المقدونية الرابعة وإنشاء مقاطعة مقدونيا الرومانية. ',
 'اللِحام هي عملية تصنيعية يتم فيها وصل مادتين عادةً من الفلزات أو اللدائن الحرارية باستخدام الحرارة لصهر أطراف المادتين سويًّا، أحيانًا ما تكون مصحوبة بضغط خارجي، ثم تركهما يبردان، مما يعطيهما صلادة دائمة. تختلف عملية اللحام عن عمليات وصل المواد الأخرى التي تتم في درجات حرارة كعمليات لحام الخلط واللحام بالقصدير، والتي لا يصحبها انصهار للمواد المراد وصلها. \nبالإضافة إلى صهر المادة الأصلية، يتم إضافة مادة حشو عادةً إلى وصلة اللحام لتُكوّن بركة من المعدن المنصهر (بركة لحام ) عند تجمُّدها تجعل وصلة اللحام أيًّا كان تصميمها أقوى من المادة الأصلية الملحومة. كذا، بالإمكان استخدام ضغط خارجي مع الحرارة، أو ضغط خارجي فقط للحام مادتين. كما تتطلب عملية اللحام عادةّ درعًا ما لحماية مادة الحشو أو المواد المذابة من أن تتلوّث أو تتأكسد. \nتستخدم مصادر عدة للطاقة في عمليات اللحام كيميائية كاللهب الغازي، أو كهربائية كالقوس الكهربي، أو الليزر، أو الحزم الإلكترونية، أو الاحتكاك الميكانيكي، أو الموجات فوق الصوتية. وبعيدًا عن العمليات الصناعية، يمكن أن يتم اللحام أوساط متعددة كالهواء الطلق أو تحت الماء  أو في الفضاء الخارجي. ويعد اللحام عملية خطيرة تستلزم اتخاذ احتياطات ضرورية لتجنب الحروق أو الصدمات الكهربية أو تلف البصر أو استنشاق الغازات والأبخرة السامة أو التعرض للأشعة فوق البنفسجية بكثافة. ',
 'إن موقعَ هانفورد هو مخبر خارج عن الخدمة لتركيب الوقود النووي، على نهر كولومبيا في وسط جنوب ولاية واشنطن، والمشغل من قبل الحكومةِ الأمريكية الفيدرالية. أسس في عام 1943 كجزء مِنْ مشروع مانهاتن، وكان الموقع مقراً لمفاعل B، وهو أول مفاعل لإنتاجِ البلوتونيومِ في العالم. استخدم البلوتونيوم المصنع في هذا الموقع في أول قنبلة نووية، اختبرت في تجربة موقع ترينيتي، وفي قنبلة فات مان التي ألقيت على ناغازاكي في اليابان. ',
 'كانت ماري جين ريتشاردسون جونز (1819 – 26 ديسمبر 1909) داعية إلى إبطال العبودية، وفاعلة خير، ومناصرة لحق المرأة في الاقتراع وناشطة أمريكية. \nوُلدت في تينيسي، وانتقلت إلى إلينوي مع عائلتها في سنيّ مراهقتها، حيث عاشت بقية حياتها. إلى جانب زوجها جون جونز، كانت شخصية إفريقية أمريكية رائدة في التاريخ المبكر لشيكاغو ومواطنة بارزة في المدينة. بعد وفاته في 1879، استمرت في دعم قضيته في الحقوق المدنية للأفارقة الأمريكيين والنهضة في شيكاغو، بالإضافة إلى الصيرورة مناصرة لحق المرأة في الاقتراع. وصفتها المؤرخة واندا أيه. هندريكس بكونها «أمّ رئيسة أرستقراطية ثرية، ترأست النخبة السوداء في لعقدين من الزمن» ',
 'عادة بيع الزوجة هي وسيلة بديلة للطلاق حيث كان الطلاق ذاته في ذلك الحين شيئًا يستحيل تطبيقه عمليًا بالنسبة للجميع عدا الأسر الأغنى ببريطانيا وخاصةً إنجلترا. بدأت تلك العادة بالظهور في أواخر القرن السابع عشر، وكانت تتم عبر موافقة كلا الطرفين لوضع حد للزواج المضطرب. يقوم الزوج بربط زوجه بحبل إما حول الرقبة أو الذراع أو الخصر واستعراضها جهارًا في مزاد علني ليبيعها إلى المزايد الذي يقدم أكبر قدر من المال. إن ذلك العرف يعرض لأحداث رواية «عمدة كاستربريدج» للروائي الشهير توماس هاردي حيث تقوم الشخصية المحورية ببيع زوجها في مطلع الرواية، الأمر الذي من شأنه أن يطارده طيلة حياته، وأخيرًا يؤدي إلى القضاء عليه. \nوعلى الرغم من كون ذلك العرف غير رسمي وادى في كثير من الأحيان إلى رفع دعاوٍ قضائية، وخاصًة بدايًة من منتصف القرن التاسع عشر وحتى الوقت الحالي، فإن موقف السلطات من العرف السائد يبدو مبهمًا. وقد صرح أحد قضاة القرن التاسع عشر في تدوين له بعدم امتلاكه الصلاحيات لمنع بيع الأزواج. وقد كانت هناك بعض الدعاوي التي يتولاها مفوضو القانون للفقراء المحليين نصت على إجبار الأزواج على بيع زوجاتهم فضلًا عن إبقاء عائلاتهم في الإصلاحية. \nاستمرت العادة الرائجة في أحد أشكالها بإنجلترا حتى أوائل القرن العشرين، هذا وقد أدلى المؤرخ والقاضي جيمس برايس في كتاباته لعام 1901 أن تلك العادة قد كانت متداولة في عهده. \n\n ',
 ' تأثير حروف الاسم هي ظاهرة تُوَضِّح الاتجاه الباطن عند الناس لتفضيل الحروف الواردة في أسمائهم على باقي الحروف الألفبائية الأخرى. فعندما يُطلب من المشاركين ترتيب جميع الحروف الأبجدية، أو إعطاء كل حرف من الحروف درجة، أو اختيار الحرف الذي يُفضلونه من مجموعة من اثنين، أو اختيار مجموعة صغيرة من الحروف التي يفضلونها، ففي العادة يختار الأشخاص الحروف الواردة بأسمائهم أكثر من غيرها. والأهم من ذلك أن الأشخاص لا يُدركون أنهم يختارون حروفاً من أسمائهم. \nاكتشفَ هذه الظاهرة عالم النفس البلجيكي جوزيف نوتين  في عام 1985، وقد ورد مصطلح «تأثير حروف الاسم» في عشرات الدراسات لموضوعات في أكثر من 15 دولة. وهو لا يتوقف على العمر أو نوع الجنس. حتى إن الأشخاص الذين غيروا أسماءهم منذ سنوات عديدة يميلون إلى تفضيل الحروف الواردة في كل من الأسماء الحالية والأصلية على غيرها من الحروف. ويظهر التأثير بصورة أبرز للأحرف الأولى، ولكن حتى عندما يجري استبعاد الأحرف الأولى، تظل الحروف المتبقية من كل من الاسم وأسماء العائلة هي المُفَضَّلَة على باقي الحروف. ',
 'اجتمعوا معًا على اسمي هي رواية صدرت عام 1974 في شكل مذكرات للكاتبة والشاعرة (مايا أنجيلو)، وتعد الرواية هي الكتاب الثاني من سلسلة كتب من سبع أجزاء لسيرتها الذاتية، حيث كتبت هذه الرواية بعد ثلاث سنوات من كتابها الأول (الطائر الحبيس). يبدأ الكتاب مباشرة من حيث توقفت الأحداث في الجزء الأول (أعرف لماذا يغرد الطائر الحبيس) ويتتبع قصة حياة (أنجيلو) – والتي تدعى «ريتا» -من عمر السابعة عشر حتى التاسعة عشر، حيث يصور الكتاب «انحدار أم وحيدة إلى أسفل السلم الاجتماعى حيث الفقر والجريمة». وعلى الرغم من أن العنوان اقتبس من الإنجيل، لكنه أيضًا يصور حياة امرأة ذات بشرة سوداء تعيش في ظل مجتمع أمريكي يسيطر عليه البيض بعد الحرب العالمية الثانية. \n\n ',
 ' كان الربيع الكرواتي نزاعًا سياسيًا استمر منذ عام 1967 حتى عام 1971 في جمهورية كرواتيا الاشتراكية؛ والتي تُعد حاليًا جزءًا من جمهورية يوغوسلافيا الاشتراكية الاتحادية. كانت كرواتيا واحدة من جمهوريات يوغوسلافيا الست في ذلك الوقت، ووقعت تحت حكم رابطة شيوعيي كرواتيا، المستقلة اسميًا عن رابطة شيوعيي يوغوسلافيا، بقيادة الرئيس جوزيف بروز تيتو. تميزت ستينيات القرن العشرين في يوغوسلافيا بسلسلة من الإصلاحات التي تهدف إلى تحسين الوضع الاقتصادي في البلاد والجهود المسيّسة بشكل متزايد من قبل قيادة الجمهوريات لحماية المصالح الاقتصادية لجمهورياتهم. حدث الصراع السياسي في كرواتيا عندما دخل الإصلاحيون ضمن رابطة شيوعيي كرواتيا، المتحالفين بشكل عام مع المجموعة الثقافية الكرواتية ماتيكا هرفاتسكا، في صراع مع المحافظين. ',
 'المُخَيخ (اللاتينيّة: Cerebellum والتي تعني «الدماغ الصغير») مَعَلمٌ رئيسيّ في الدماغ الخلفيّ لجميع الفقاريات. على الرغم من أنه عادةً أصغر من المخ، إلا أنه في بعض الحيوانات كالأسماك القنومية قد يكون كبيراً كالمخ أو أكبر حتَّى. عند البشر يلعب المخيخ دوراً هاماً في التحكُّم الحركيّ وقد يكون أيضاً مشتركاً في بعض الوظائف المعرفيّة كالانتباه واللغة وكذلك في تنظيم استجابات الرضا والخوف، ولكن وظائفه المرتبطة بالحركة هي الأكثر رسوخاً. لا يبدأ المخيخ البشريّ الحركة، ولكنه يساهم في تنسيقها ودقتها وإحكام التوقيت: يتلقى المُدخَلات من الأجهزة الحسيّة للحبل الشوكيّ ومن أجزاء الدماغ الأخرى، ومن ثُمَّ يقوم بإجراء بعض التعديلات على هذه المُدخَلات ليصقل النشاط الحركيّ. تؤدِّي الأذية المخيخيّة إلى اضطرابات في الحركة الدقيقة والتوازن ووضعيّة الجسد وتعلُّم الحركات عند البشر. ',
 'مؤتمر نيون هو مؤتمر دبلوماسي انعقد في نيون، سويسرا في سبتمبر 1937 بشأن الهجمات التي وقعت على النقل البحري الدولي في البحر الأبيض المتوسط أثناء الحرب الأهلية الإسبانية. وقد انعقد المؤتمر جزئيًا إلى حد لأن إيطاليا كانت قد شنت حرب غواصات غير محدودة، على الرغم من أن ائتلاف المؤتمر الختامي لم يتهم إيطاليا بذلك مباشرة؛ وبدلًا من ذلك أشير إلى تلك الهجمات باعتبارها «قرصنة» قامت بها جهة مجهولة الهوية. وهدف المؤتمر إلى تعزيز سياسة عدم التدخل في الحرب الأهلية الإسبانية، قاد المؤتمر كل من المملكة المتحدة وفرنسا، وحضره أيضًا بلغاريا، مصر، اليونان، رومانيا، تركيا، الاتحاد السوفياتي، ويوغوسلافيا. ',
 'رواد عربة اليد المورمونية هم الأفراد المشاركين في هجرة أعضاء كنيسة يسوع المسيح لقديسي الأيام الأخيرة إلى سولت ليك سيتي، بولاية يوتا، مستخدمين عربات يدوية لنقل أمتعتهم. \nبدأت حركة عربة اليد المورمونية في عام 1856 واستمرت حتى عام 1860. \nبدافع للانضمام إلى زملائهم أعضاء الكنيسة في ولاية يوتا؛ قام ما يقارب من 3000 من رواد المورمون من إنجلترا وويلز واسكتلندا واسكندنافيا بالرحلة من أيوا أو نبراسكا إلى يوتا في عشر عربات يدوية، بسبب عدم توفر المال لتجهيز فرق كاملة من الثيران أو الخيول لنقلهم. \nكانت الرحلة كارثية لفريقين من الفرق، والتي بدأت رحلتهما في وقتٍ متأخرٍ، وفاجأتهم ثلوجٌ كثيفة، وبرودة قارسة في وسط وايومنغ، وعلى الرغم من جهود الإنقاذ الدراماتيكية، توفي على طول الطريق أكثر من 210 من بين 980 رائدًا في هاتين الفرقتين. كتب أحد الناجين جون تشيسليت: «سحب العديد من الآباء عرباتهم التي تحمل أطفالهم الصغار، حتى اليوم السابق لوفاتهم». \n\n ',

In [ ]:
bleu = BLEU()
bleu_score = bleu.corpus_score(translations, [references]).score
print(f"Overall BLEU score for subset: {bleu_score:.2f}")

Overall BLEU score for subset: 22.83

In [ ]:
data = [
    {"src": row['english_text'], "mt": row['agent_translation'], "ref": row['arabic_reference']}
    for _, row in test_df_translated.iterrows()]

In [ ]:
model_path = download_model("Unbabel/wmt22-comet-da")
model = load_from_checkpoint(model_path)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Fetching 5 files:   0%|          | 0/5 [00:00<?, ?it/s]

README.md: 0.00B [00:00, ?B/s]

hparams.yaml:   0%|          | 0.00/567 [00:00<?, ?B/s]

LICENSE: 0.00B [00:00, ?B/s]

.gitattributes: 0.00B [00:00, ?B/s]

checkpoints/model.ckpt:   0%|          | 0.00/2.32G [00:00<?, ?B/s]

INFO:pytorch_lightning.utilities.migration.utils:Lightning automatically upgraded your loaded checkpoint from v1.8.3.post1 to v2.5.5. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ../root/.cache/huggingface/hub/models--Unbabel--wmt22-comet-da/snapshots/2760a223ac957f30acfb18c8aa649b01cf1d75f2/checkpoints/model.ckpt`

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.10M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/616 [00:00<?, ?B/s]

/usr/local/lib/python3.12/dist-packages/pytorch_lightning/core/saving.py:195: Found keys that are not in the model state dict but in the checkpoint: ['encoder.model.embeddings.position_ids']

In [ ]:
comet_scores = model.predict(data, batch_size=8, gpus=0)

INFO:pytorch_lightning.utilities.rank_zero:💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
INFO:pytorch_lightning.utilities.rank_zero:GPU available: False, used: False
INFO:pytorch_lightning.utilities.rank_zero:TPU available: False, using: 0 TPU cores
INFO:pytorch_lightning.utilities.rank_zero:HPU available: False, using: 0 HPUs
Predicting DataLoader 0: 100%|██████████| 5/5 [05:59<00:00, 71.82s/it]

In [ ]:
print(f"Overall COMET score for subset: {comet_scores.system_score:.4f}")

Overall COMET score for subset: 0.8629